--[[

	Atlas, a World of Warcraft instance map browser
	Email me at m4r3lk4@gmail.com

	This file is part of Atlas.

	Atlas is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	Atlas is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Atlas; if not, write to the Free Software
	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

--]]

-- Atlas Data
-- Compiled by Dan Gilbert
-- loglow@gmail.com
-- Many thanks to all contributors!
-- Now with GUIDs!
-- Now externally localized!

local AL = AceLibrary("AceLocale-2.2"):new("Atlas");
local BC = AceLibrary("Babble-Class-2.2")
--local BZ = AceLibrary("Babble-Zone-2.2")
--local BB = AceLibrary("Babble-Boss-2.2")
local BF = AceLibrary("Babble-Faction-2.2")
local BIS = AceLibrary("Babble-ItemSet-2.2")

local BLUE = "|cff6666ff";
local GREY = "|cff999999";
local GREN = "|cff66cc33";
local _RED = "|cffcc6666";
local ORNG = "|cffcc9933";
local PURP = "|cff9900ff";
local WHIT = "|cffffffff";
local INDENT = "      ";

local ZONE = 1;
local NPC = 2;
local ITEM = 3;
local OBJECT = 4;
local FACTION = 5;
local QUEST = 6;

AtlasMaps = {

--************************************************
-- Kalimdor Instances
--************************************************

	RagefireChasm = {
		ZoneName = { AL["Ragefire Chasm"], 2437 };
		Acronym = "RFC";
		Location = { AL["Orgrimmar"], 1637 };
		LevelRange = "13-18";
		MinLevel = "8";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Maur Grimtotem"], NPC, 11834 };
		{ GREY..INDENT..AL["Oggleflint"], NPC, 11517 };
		{ GREY.."2) "..AL["Taragaman the Hungerer"], NPC, 11520 };
		{ GREY.."3) "..AL["Jergosh the Invoker"], NPC, 11518 };
		{ GREY.."4) "..AL["Bazzalan"], NPC, 11519 };
	};
	WailingCaverns = {
		ZoneName = { AL["Wailing Caverns"], 718 };
		Acronym = "WC";
		Location = { AL["The Barrens"], 17 };
		LevelRange = "17-24";
		MinLevel = "10";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Disciple of Naralex"], NPC, 3678 };
		--{ GREY..INDENT..AL["Mysterious Wailing Caverns Chest"], OBJECT, 180055 };
		{ GREY.."2) "..AL["Lord Cobrahn"], NPC, 3669 };
		{ GREY.."3) "..AL["Lady Anacondra"], NPC, 3671 };
		{ GREY.."4) "..AL["Kresh"], NPC, 3653 };
		{ GREY.."5) "..AL["Deviate Faerie Dragon"].." ("..AL["Rare"]..")", NPC, 5912 };
		{ GREY.."6) ".."Zandara Windhoof", NPC, -1 };
		{ GREY.."7) "..AL["Lord Pythas"], NPC, 3670 };
		{ GREY.."8) "..AL["Skum"], NPC, 3674 };
		{ GREY.."9) ".."Vangros", NPC, -1 };
		{ GREY.."10) "..AL["Lord Serpentis"].." ("..AL["Upper"]..")", NPC, 3673 };
		{ GREY.."11) "..AL["Verdan the Everliving"].." ("..AL["Upper"]..")", NPC, 5775 };
		{ GREY.."12) "..AL["Mutanus the Devourer"], NPC, 3654 };
		{ GREY..INDENT..AL["Naralex"], NPC, 3679 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Embrace of the Viper"] };
	};
	BlackfathomDeeps = {
		ZoneName = { AL["Blackfathom Deeps"], 719 };
		Acronym = "BFD";
		Location = { AL["Ashenvale"], 331 };
		LevelRange = "24-32";
		MinLevel = "19";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Ghamoo-ra"], NPC, 4887 };
		{ GREY.."2) "..AL["Lorgalis Manuscript"], ITEM, 5359 };
		{ GREY.."3) "..AL["Lady Sarevess"], NPC, 4831 };
		{ GREY.."4) "..AL["Argent Guard Thaelrid"], NPC, 4787 };
		{ GREY.."5) "..AL["Gelihast"], NPC, 6243 };
		{ GREY..INDENT..AL["Shrine of Gelihast"] };
		{ GREY.."6) "..AL["Lorgus Jett"].." ("..AL["Varies"]..")", NPC, 12902 };
		{ GREY.."7) "..AL["Baron Aquanis"], NPC, 12876 };
		{ GREY..INDENT..AL["Fathom Stone"], OBJECT, 177964 };
		{ GREY.."8) "..AL["Velthelaxx the Defiler"], NPC, -1 };
		{ GREY.."9) "..AL["Twilight Lord Kelris"], NPC, 4832 };
		{ GREY.."10) "..AL["Old Serra'kis"], NPC, 4830 };
		{ GREY.."11) "..AL["Aku'mai"], NPC, 4829 };
		{ GREY..INDENT..AL["Morridune"], NPC, 6729 };
		{ GREY..INDENT..AL["Altar of the Deeps"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	--FrostmaneHollow TurtleWOW 1.18.1
	FrostmaneHollow = {
		ZoneName = { AL["Frostmane Hollow"],  };
		Acronym = "FMH";
		Location = { AL["Dun Morogh"], 1 };
		LevelRange = "13-20";
		MinLevel = "8";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Nimble Tansha"], NPC, -1 };
		{ "" };
		{ GREY.."2) "..AL["Ubbukaz Battlefield Overlord"], NPC, -1 };
		{ GREY.."3) "..AL["Prophet Kanza"], NPC, -1 };
		{ GREY.."4) "..AL["Cold Haile"], NPC, -1 };
	};
	--TimbermawHold TurtleWOW 1.18.1
	TimbermawHold = {
		ZoneName = { AL["Timbermaw Hold"],  };
		Acronym = "TMH";
		Location = { AL["Azshara"], 31 };
		LevelRange = "60";
		MinLevel = "60";
		PlayerLimit = "20";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Karrsh the Sentinel"], NPC, -1 };
		{ GREY.."2) "..AL["Rotgrowl"], NPC, -1 };
		{ GREY.."3) "..AL["Trioch the Devourer"], NPC, -1 };
		{ GREY.."4) "..AL["Ormanos the Cracked"], NPC, -1 };
		{ GREY.."5) "..AL["Loktanag the Vile"], NPC, -1 };
		{ GREY.."6) "..AL["Chieftain Partath"], NPC, -1 };
		{ GREY.."7) "..AL["Selenaxx Foulheart"], NPC, -1 };
		{ GREY.."8) "..AL["Archdruid Kronn"], NPC, -1 };
		{ GREY.."9) "..AL["Ursol"], NPC, -1 };
		{ GREY.."10) "..AL["Perotharn"].." (".."隐藏BOSS"..")", NPC, -1 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	-- WindhornCanyon TurtleWOW 1.18.1
    WindhornCanyon = {
        -- ZoneID 如果你没有（私服自定义副本常没有），这里可以像其它 TurtleWOW 副本那样留空
        ZoneName = { AL["Windhorn Canyon"],  };
        Acronym = "WSC";
        -- 地点：需要你确定入口在哪个大地图（例如 The Barrens / Stonetalon / Desolace 等）
        -- 下面先按 The Barrens 示例，你可以改
        Location = { AL["Thousand Needles"], 400 };
        LevelRange = "26-30";
        MinLevel = "26";
        PlayerLimit = "5";
        Continent = AL["Kalimdor"];

        { BLUE.."A) "..AL["Entrance"] };

        -- 下面这些按你 Instances.lua/AtlasLoot 的boss列表先占位
        -- 你如果有准确 NPCID，可以把 NPC, -1 改成真实ID
        { GREY.."1) "..AL["Pathun Buskhide"], NPC, -1 };
        { GREY.."2) "..AL["Ahgk'tos the Pure"], NPC, -1 };
        { GREY.."3) "..AL["Ambassador Vortalus"], NPC, -1 };
        { GREY.."4) "..AL["Walgan Bloodcaller"], NPC, -1 };
        { GREY.."5) "..AL["Bonespeaker Narlgom"], NPC, -1 };
        { GREY.."6) "..AL["Prophet Stormhoof"], NPC, -1 };
        { GREY.."7) "..AL["Chieftain Shalk Blackwind"], NPC, -1 };

        { "" };
        { GREY..INDENT..AL["Trash Mobs"] };
    };
	-- TheCrescentGrove TurtleWOW
	TheCrescentGrove = {
		ZoneName = { AL["The Crescent Grove"],  };
		Acronym = "CG";
		Location = { AL["Ashenvale"], 331 };
		LevelRange = "32-38";
		MinLevel = "32";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ INDENT..GREY.."a) "..AL["Kalanar's Strongbox"], OBJECT, 2010860 };
		{ GREY.."1) "..AL["Grovetender Engryss"], NPC, 92107 };
		{ GREY.."2) "..AL["Keeper Ranathos"], NPC, 92109 };
		{ GREY.."3) "..AL["High Priestess A'lathea"], NPC, 92108 };
		{ GREY.."4) "..AL["Fenektis the Deceiver"], NPC, 92111 };
		{ GREY.."5) "..AL["Master Raxxieth"], NPC, 92110 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	--HateforgeQuarry TurtleWOW
	HateforgeQuarry = {
		ZoneName = { AL["Hateforge Quarry"],  };
		Acronym = "HFQ";
		Location = { AL["Burning Steppes"], 46 };
		LevelRange = "52-60";
		MinLevel = "48";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["High Foreman Bargul Blackhammer"], NPC, 60735 };
		{ GREY.."2) "..AL["Engineer Figgles"], NPC, 60736 };
		{ INDENT..GREY.."a) "..AL["Hateforge Chemistry Documents"] };
		{ GREY.."3) "..AL["Corrosis"], NPC, 60829 };
		{ GREY.."4) "..AL["Hatereaver Annihilator"], NPC, 60734 };
		{ GREY.."5) "..AL["Hargesh Doomcaller"], NPC, 60737 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	--KarazhanCrypt TurtleWOW
	KarazhanCrypt = {
		ZoneName = { AL["Karazhan Crypt"],  };
		Acronym = "Kara Crypt";
		Location = { AL["Deadwind Pass"], 41 }; -- ["Deadwind Pass"], 41 -- ["Burning Steppes"], 46
		LevelRange = "58-60";
		MinLevel = "58";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Marrowspike"], NPC, 91920 };
		{ GREY.."2) "..AL["Hivaxxis"], NPC, 91929 };
		{ GREY.."3) "..AL["Corpsemuncher"], NPC, 91917 };
		{ GREY.."4) "..AL["Guard Captain Gort"], NPC, 92935 };
		{ GREY.."5) "..AL["Archlich Enkhraz"], NPC, 91916 };
		{ GREY.."6) "..AL["Commander Andreon"], NPC, 91919 }; -- Commander Andreon not Commander Anderson. AtlasLoot name misstake
		{ GREY.."7) "..AL["Alarus"], NPC, 91928 };
		{ GREY.."8) "..AL["Half-Buried Treasure Chest"], OBJECT, 379545 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	--CavernsOfTimeBlackMorass TurtleWOW
	CavernsOfTimeBlackMorass = {
		ZoneName = { AL["Black Morass"],  };
		Acronym = "BM";
		Location = { AL["Tanaris"], 440 };
		LevelRange = "60-60";
		MinLevel = "58";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ GREY.."1) "..AL["Chronar"], NPC, 65113 };
		{ GREY.."2) "..AL["Epidamu"], NPC, 61575 };
		{ GREY.."3) "..AL["Drifting Avatar of Sand"], NPC, 61316 };
		{ GREY.."4) "..AL["Time-Lord Epochronos"], NPC, 65116 };
		{ GREY.."5) "..AL["Mossheart"], NPC, 65124 };
		{ GREY.."6) "..AL["Antnormi"], NPC, 65125 };
		{ GREY.."7) "..AL["Rotmaw"], NPC, 65122 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	--StormwindVault TurtleWOW
	StormwindVault = {
		ZoneName = { AL["Stormwind Vault"],  };
		Acronym = "SWV";
		Location = { AL["Stormwind City"], 1519 };
		LevelRange = "60-60";
		MinLevel = "58";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Aszosh Grimflame"], NPC, 80853 };
		{ GREY.."2) "..AL["Tham'Grarr"], NPC, 80852 };
		{ GREY.."3) "..AL["Black Bride"], NPC, 80850 };
		{ GREY..INDENT..AL["Tome of Arcane Intricacies and Magical Phenomenon IX"]};
		{ GREY.."4) "..AL["Damian"], NPC, 80854 };
		{ GREY.."5) "..AL["Volkan Cruelblade"], NPC, 80851 };
		{ GREY.."6) "..AL["Arc'tiras"], NPC, 93107 };
		{ GREY.."7) "..AL["Vault Armory Equipment"], NPC, -1 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
		--GilneasCity TurtleWOW
	GilneasCity = {
		ZoneName = { AL["Gilneas City"],  };
		Acronym = "GC";
		Location = { AL["Gilneas"], };
		LevelRange = "43-49";
		MinLevel = "43";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Matthias Holtz"], NPC, 61419 };
		{ GREY.."2) "..AL["Packmaster Ragetooth"], NPC, 61420 };
		{ INDENT..GREY.."a) "..AL["Dawnstone Plans"]};
		{ INDENT..GREY.."b) "..AL["Manuscript of Hydromancy II"]};
		{ GREY.."3) "..AL["Judge Sutherland"], NPC, 61421 };
		{ GREY.."4) "..AL["Dustivan Blackcowl"], NPC, 61422 };
		{ GREY.."5) "..AL["Marshal Magnus Greystone"], NPC, 61423 };
		{ GREY.."6) "..AL["Horsemaster Levvin"], NPC, 61605 };
		{ GREY.."7) "..AL["Harlow Family Chest"], OBJECT, 2020027 };
		{ GREY.."8) "..AL["Genn Greymane"], NPC, 61418 };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
		--LowerKara TurtleWOW
	LowerKara = {
		ZoneName = { AL["Lower Karazhan Halls"],  };
		Acronym = "LKH";
		Location = { AL["Deadwind Pass"], 41};
		LevelRange = "58-60";
		MinLevel = "58";
		PlayerLimit = "10";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ GREY.."1) "..AL["Master Blacksmith Rolfen"], NPC, 61319 };
		{ GREY..INDENT.."a) "..AL["Engraved Golden Bracelet"] };
		{ GREY..INDENT.."b) "..AL["Comfortable Pillow"] };
		{ GREY.."2) "..AL["Brood Queen Araxxna"], NPC, 61221 };
		{ GREY.."3) "..AL["Grizikil"], NPC, 61224 };
		{ GREY..INDENT.."c) "..AL["Councilman Kyleson"] };
		{ GREY.."4) "..AL["Clawlord Howlfang"], NPC, 61223 };
		{ GREY.."5) "..AL["Lord Blackwald II"], NPC, 61222 };
		{ GREY..INDENT.."d) "..AL["Lord Ebonlocke"] };
		{ GREY..INDENT.."e) "..AL["Obsidian Rod"] };
		{ GREY..INDENT.."f) "..AL["Duke Rothlen"] };
		{ GREY.."6) "..AL["Moroes"], NPC, 61226 };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["LKH Enchants"] };
	};
    UpperKara = {
		ZoneName = { AL["Tower of Karazhan"], };
		Acronym = "Kara40";
		Location = { AL["Deadwind Pass"], 41};
		LevelRange = "60";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ "" };
		{ "" };
		{ GREY.."1) "..AL["Keeper Gnarlmoon"], NPC, -1 };
		{ GREY.."2) "..AL["Ley-Watcher Incantagos"], NPC, -1 };
		{ GREY.."3) "..AL["Anomalus"], NPC, -1 };
		{ GREY.."4) "..AL["Echo of Medivh"], NPC, -1 };
		{ GREY.."5) "..AL["King"], NPC, -1 };
		{ GREY.."6) "..AL["Sanv Tas'dal"], NPC, -1 };
		{ GREY.."7) "..AL["Rupturan the Broken"], NPC, -1 };
		{ GREY.."8) "..AL["Kruul"], NPC, -1 };
		{ GREY.."9) "..AL["Mephistroth"], NPC, -1 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	-- EmeraldSanctum TurtleWOW
	EmeraldSanctum = {
		ZoneName = { AL["Emerald Sanctum"],  };
		Acronym = "ES";
		Location = { AL["Hyjal"], };
		LevelRange = "58-60";
		MinLevel = "58";
		PlayerLimit = "40";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Erennius"], NPC, 60747 };
		{ GREY.."2) "..AL["Solnius the Awakener"], NPC, 60748 };
		{ GREY..INDENT..AL["Favor of Erennius (ES Hard Mode)"], OBJECT, 2020042 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	RazorfenKraul = {
		ZoneName = { AL["Razorfen Kraul"], 491 };
		Acronym = "RFK";
		Location = { AL["The Barrens"], 17 };
		LevelRange = "29-38";
		MinLevel = "19";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Roogug"], NPC, 6168 };
		{ GREY.."2) "..AL["Aggem Thorncurse"], NPC, 4424 };
		{ GREY.."3) "..AL["Death Speaker Jargba"], NPC, 4428 };
		{ GREY.."4) "..AL["Overlord Ramtusk"], NPC, 4420 };
		{ GREY..INDENT..AL["Razorfen Spearhide"].." ("..AL["Rare"]..")", NPC, 4438 };
		{ GREY.."5) "..AL["Agathelos the Raging"], NPC, 4422 };
		{ GREY.."6) "..AL["Blind Hunter"].." ("..AL["Rare"]..")", NPC, 4425 };
		{ GREY.."7) "..AL["Charlga Razorflank"], NPC, 4421 };
		{ GREY.."8) "..AL["Willix the Importer"], NPC, 4508 };
		{ GREY..INDENT..AL["Heralath Fallowbrook"], NPC, 4510 };
		{ GREY.."9) "..AL["Earthcaller Halmgar"].." ("..AL["Rare"]..")", NPC, 4842 };
		{ GREY.."10) "..AL["Rotthorn"], NPC, -1 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	RazorfenDowns = {
		ZoneName = { AL["Razorfen Downs"], 722 };
		Acronym = "RFD";
		Location = { AL["The Barrens"], 17 };
		LevelRange = "37-46";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Tuten'kash"], NPC, 7355 };
		{ GREY.."2) "..AL["Henry Stern"], NPC, 8696 };
		{ GREY..INDENT..AL["Belnistrasz"], NPC, 8516 };
		{ GREY..INDENT..AL["Sah'rhee"], NPC, 8767 };
		{ GREY..INDENT..AL["Lady Falther'ess"].." ("..AL["Scourge Invasion"]..")", NPC, 14686 };
		{ GREY.."3) "..AL["Mordresh Fire Eye"], NPC, 7357 };
		{ GREY.."4) "..AL["Glutton"], NPC, 8567 };
		{ GREY.."5) "..AL["Ragglesnout"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 7354 };
		{ GREY.."6) "..AL["Death Prophet Rakameg"], NPC, -1 };
		{ GREY.."7) "..AL["Amnennar the Coldbringer"], NPC, 7358 };
		{ GREY.."8) "..AL["Plaguemaw the Rotting"], NPC, 7356 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	ZulFarrak = {
		ZoneName = { AL["Zul'Farrak"], 978 };
		Acronym = "ZF";
		Location = { AL["Tanaris"], 440 };
		LevelRange = "44-54";
		MinLevel = "30";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Key"]..": "..AL["Mallet of Zul'Farrak"].." ("..AL["Gahz'rilla"]..")", ITEM, 9240 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Zerillis"].." ("..AL["Rare"]..", "..AL["Wanders"]..")", NPC, 10082 };
		{ GREY.."2) "..AL["Antu'sul"], NPC, 8127 };
		{ GREY.."3) "..AL["Theka the Martyr"], NPC, 7272 };
		{ GREY.."4) "..AL["Witch Doctor Zum'rah"], NPC, 7271 };
		{ GREY..INDENT..AL["Zul'Farrak Dead Hero"], NPC, 7276 };
		{ GREY.."5) "..AL["Nekrum Gutchewer"], NPC, 7796 };
		{ GREY..INDENT..AL["Shadowpriest Sezz'ziz"], NPC, 7275 };
		{ GREY..INDENT..AL["Dustwraith"].." ("..AL["Rare"]..")", NPC, 10081 };
		{ GREY.."6) "..AL["Sergeant Bly"], NPC, 7604 };
		{ GREY..INDENT..AL["Weegli Blastfuse"], NPC, 7607 };
		{ GREY..INDENT..AL["Murta Grimgut"], NPC, 7608 };
		{ GREY..INDENT..AL["Raven"], NPC, 7605 };
		{ GREY..INDENT..AL["Oro Eyegouge"], NPC, 7606 };
		{ GREY..INDENT..AL["Sandfury Executioner"], NPC, 7274 };
		{ GREY.."7) "..AL["Chief Ukorz Sandscalp"], NPC, 7267 };
		{ GREY..INDENT..AL["Ruuzlu"], NPC, 7797 };
		{ GREY.."8) "..AL["Hydromancer Velratha"], NPC, 7795 };
		{ GREY..INDENT..AL["Gahz'rilla"].." ("..AL["Summon"]..")", NPC, 7273 };
		{ GREY..INDENT..AL["Elder Wildmane"].." ("..AL["Lunar Festival"]..")", NPC, 15578 };
		{ GREY.."9) "..AL["Zel'jeb the Ancient"], NPC, -1 };
		{ GREY.."10) "..AL["Champion Razjal the Quick"], NPC, -1 };
		{ GREY..INDENT..AL["Sandarr Dunereaver"].." ("..AL["Rare"]..")", NPC, 10080 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	Maraudon = {
		ZoneName = { AL["Maraudon"], 2100 };
		Acronym = "Mara";
		Location = { AL["Desolace"], 405 };
		LevelRange = "46-55";
		MinLevel = "35";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Key"]..": "..AL["Scepter of Celebras"].." ("..AL["Portal"]..")", ITEM, 17191 };
		{ BLUE.."A) "..AL["Entrance"].." ("..AL["Orange"]..")" };
		{ BLUE.."B) "..AL["Entrance"].." ("..AL["Purple"]..")" };
		{ BLUE.."C) "..AL["Entrance"].." ("..AL["Portal"]..")" };
		{ GREY.."1) "..AL["Veng"], NPC, 13738 };
		{ GREY.."2) "..AL["Noxxion"], NPC, 13282 };
		{ GREY.."3) "..AL["Razorlash"], NPC, 12258 };
		{ GREY.."4) "..AL["Maraudos"], NPC, 13739 };
		{ GREY.."5) "..AL["Lord Vyletongue"], NPC, 12236 };
		{ GREY.."6) "..AL["Meshlok the Harvester"].." ("..AL["Rare"]..")", NPC, 12237 };
		{ GREY.."7) "..AL["Celebras the Cursed"], NPC, 12225 };
		{ GREY.."8) "..AL["Landslide"], NPC, 12203 };
		{ GREY.."9) "..AL["Tinkerer Gizlock"], NPC, 13601 };
		{ GREY.."10) "..AL["Rotgrip"], NPC, 13596 };
		{ GREY.."11) "..AL["Princess Theradras"], NPC, 12201 };
		{ GREY.."12) "..AL["Elder Splitrock"].." ("..AL["Lunar Festival"]..")", NPC, 15556 };
	};
	DireMaulEast = {
		ZoneName = { AL["Dire Maul"].." ("..AL["East"]..")", 2557 };
		Acronym = "DME";
		Location = { AL["Feralas"], 357 };
		LevelRange = "55-58";
		MinLevel = "50";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Key"]..": "..AL["Brazier of Invocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Entrance"] };
		{ BLUE.."C) "..AL["Entrance"] };
		{ BLUE.."D) "..AL["Exit"] };
		{ GREY.."1) "..AL["Pusillin"].." ("..AL["Chase Begins"]..")", NPC, 14354 };
		{ GREY.."2) "..AL["Pusillin"].." ("..AL["Chase Ends"]..")", NPC, 14354 };
		{ GREY.."3) "..AL["Zevrim Thornhoof"], NPC, 11490 };
		{ GREY..INDENT..AL["Hydrospawn"], NPC, 13280 };
		{ GREY..INDENT..AL["Lethtendris"], NPC, 14327 };
		{ GREY..INDENT..AL["Pimgib"], NPC, 14349 };
		{ GREY.."4) "..AL["Old Ironbark"], NPC, 11491 };
		{ GREY.."5) "..AL["Alzzin the Wildshaper"], NPC, 11492 };
		{ GREY..INDENT..AL["Isalien"].." ("..AL["Summon"]..")", NPC, 16097 };
		{ GREY..INDENT..AL["Felvine Shard"], OBJECT, 179559 };
		{ GREN.."1') "..AL["A Dusty Tome"].." ("..AL["Varies"]..")", OBJECT, 179547 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Dire Maul Books"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
	};
	DireMaulNorth = {
		ZoneName = { AL["Dire Maul"].." ("..AL["North"]..")", 2557 };
		Acronym = "DMN";
		Location = { AL["Feralas"], 357 };
		LevelRange = "57-60";
		MinLevel = "50";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Key"]..": "..AL["Crescent Key"], ITEM, 18249 };
		{ ORNG..AL["Key"]..": "..AL["Gordok Courtyard Key"], ITEM, 18266 };
		{ ORNG..AL["Key"]..": "..AL["Gordok Inner Door Key"], ITEM, 18268 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Library"] };
		{ BLUE.."C) "..AL["Dire Maul"].." ("..AL["West"]..")", ZONE, 2557 };
		{ GREY.."1) "..AL["Guard Mol'dar"], NPC, 14326 };
		{ GREY.."2) "..AL["Stomper Kreeg"], NPC, 14322 };
		{ GREY.."3) "..AL["Guard Fengus"], NPC, 14321 };
		{ GREY.."4) "..AL["Knot Thimblejack"], NPC, 14338 };
		{ GREY..INDENT..AL["Guard Slip'kik"], NPC, 14323 };
		{ GREY.."5) "..AL["Captain Kromcrush"], NPC, 14325 };
		{ GREY.."6) "..AL["King Gordok"], NPC, 11501 };
		{ GREY..INDENT..AL["Cho'Rush the Observer"], NPC, 14324 };
		{ GREN.."1') "..AL["Library"] };
		{ GREN..INDENT..AL["Falrin Treeshaper"], NPC, 16032 };
		{ GREN..INDENT..AL["Lorekeeper Lydros"], NPC, 14368 };
		{ GREN..INDENT..AL["Lorekeeper Javon"], NPC, 14381 };
		{ GREN..INDENT..AL["Lorekeeper Kildrath"], NPC, 14383 };
		{ GREN..INDENT..AL["Lorekeeper Mykos"], NPC, 14382 };
		{ GREN..INDENT..AL["Shen'dralar Provisioner"], NPC, 14371 };
		{ GREN..INDENT..AL["Skeletal Remains of Kariel Winthalus"], OBJECT, 179544 };
		{ GREN.."2') "..AL["A Dusty Tome"].." ("..AL["Varies"]..")", OBJECT, 179547 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Dire Maul Books"] };
		{ GREY..INDENT..AL["Tribute Run"], OBJECT, 190005 };
	};
	DireMaulWest = {
		ZoneName = { AL["Dire Maul"].." ("..AL["West"]..")", 2557 };
		Acronym = "DMW";
		Location = { AL["Feralas"], 357 };
		LevelRange = "57-60";
		MinLevel = "50";
		PlayerLimit = "5";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Key"]..": "..AL["Crescent Key"], ITEM, 18249 };
		{ ORNG..AL["Key"]..": "..AL["J'eevee's Jar"].." ("..AL["Lord Hel'nurath"]..")", ITEM, 18663 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Pylons"] };
		{ BLUE.."C) "..AL["Dire Maul"].." ("..AL["North"]..")", ZONE, 2557 };
		{ GREY.."1) "..AL["Shen'dralar Ancient"], NPC, 14358 };
		{ GREY.."2) "..AL["Tendris Warpwood"], NPC, 11489 };
		{ GREY..INDENT..AL["Ancient Equine Spirit"], NPC, 14566 };
		{ GREY.."3) "..AL["Illyanna Ravenoak"], NPC, 11488 };
		{ GREY..INDENT..AL["Ferra"], NPC, 14308 };
		{ GREY.."4) "..AL["Magister Kalendris"], NPC, 11487 };
		{ GREY.."5) "..AL["Tsu'zee"].." ("..AL["Rare"]..")", NPC, 11467 };
		{ GREY.."6) "..AL["Immol'thar"], NPC, 11496 };
		{ GREY..INDENT..AL["Lord Hel'nurath"].." ("..AL["Rare"]..", "..AL["Summon"]..")", NPC, 14506 };
		{ GREY.."7) "..AL["Prince Tortheldrin"], NPC, 11486 };
		{ GREY..INDENT..AL["The Prince's Chest"], OBJECT, 179545 };
		{ GREY.."8) "..AL["Revanchion"].." ("..AL["Scourge Invasion"]..")", NPC, 11467 };
		{ GREN.."1') "..AL["Library"] };
		{ GREN..INDENT..AL["Falrin Treeshaper"], NPC, 16032 };
		{ GREN..INDENT..AL["Lorekeeper Lydros"], NPC, 14368 };
		{ GREN..INDENT..AL["Lorekeeper Javon"], NPC, 14381 };
		{ GREN..INDENT..AL["Lorekeeper Kildrath"], NPC, 14383 };
		{ GREN..INDENT..AL["Lorekeeper Mykos"], NPC, 14382 };
		{ GREN..INDENT..AL["Shen'dralar Provisioner"], NPC, 14371 };
		{ GREN..INDENT..AL["Skeletal Remains of Kariel Winthalus"], OBJECT, 179544 };
		{ GREN.."2') "..AL["A Dusty Tome"].." ("..AL["Varies"]..")", OBJECT, 179547 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Dire Maul Books"] };
	};
	OnyxiasLair = {
		ZoneName = { AL["Onyxia's Lair"], 2159 };
		Acronym = "Ony";
		Location = { AL["Dustwallow Marsh"], 15 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Attunement Required"] };
		{ ORNG..AL["Key"]..": "..AL["Drakefire Amulet"], ITEM, 16309 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Onyxian Warders"], NPC, 12129 };
		{ GREY.."2) "..AL["Whelp Eggs"] };
		{ GREY.."3) "..AL["Onyxia"], NPC, 10184 };
		{ GREY.."4) "..AL["Broodcommander Axelus"], NPC, 10184 };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Fire"] };
	};
	TheTempleofAhnQiraj = {
		ZoneName = { AL["Temple of Ahn'Qiraj"], 3428 };
		Acronym = "AQ40";
		Location = { AL["Silithus"], 1377 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Reputation"]..": "..BF["Brood of Nozdormu"], FACTION, 910 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["The Prophet Skeram"].." ("..AL["Outside"]..")", NPC, 15263 };
		{ GREY.."2) "..AL["Bug Trio"].." ("..AL["Optional"]..")" };
		{ GREY..INDENT..AL["Vem"], NPC, 15544 };
		{ GREY..INDENT..AL["Lord Kri"], NPC, 15511 };
		{ GREY..INDENT..AL["Princess Yauj"], NPC, 15543 };
		{ GREY.."3) "..AL["Battleguard Sartura"], NPC, 15516 };
		{ GREY.."4) "..AL["Fankriss the Unyielding"], NPC, 15510 };
		{ GREY.."5) "..AL["Viscidus"].." ("..AL["Optional"]..")", NPC, 15299 };
		{ GREY.."6) "..AL["Princess Huhuran"], NPC, 15509 };
		{ GREY.."7) "..AL["The Twin Emperors"] };
		{ GREY..INDENT..AL["Emperor Vek'lor"], NPC, 15276 };
		{ GREY..INDENT..AL["Emperor Vek'nilash"], NPC, 15275 };
		{ GREY.."8) "..AL["Ouro"].." ("..AL["Optional"]..")", NPC, 15517 };
		{ GREY.."9) "..AL["C'Thun"], NPC, 15589 };
		{ GREN.."1') "..AL["Andorgos"], NPC, 15502 };
		{ GREN..INDENT..AL["Vethsera"], NPC, 15504 };
		{ GREN..INDENT..AL["Kandrostrasz"], NPC, 15503 };
		{ GREN.."2') "..AL["Arygos"], NPC, 15380 };
		{ GREN..INDENT..AL["Caelestrasz"], NPC, 15379 };
		{ GREN..INDENT..AL["Merithra of the Dream"], NPC, 15378 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["AQ Enchants"] };
		{ GREY..INDENT..AL["Temple of Ahn'Qiraj Sets"] };
		{ GREY..INDENT..AL["AQ Opening Quest Chain"] };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Nature"] };
	};
	TheRuinsofAhnQiraj = {
		ZoneName = { AL["Ruins of Ahn'Qiraj"], 3429 };
		Acronym = "AQ20";
		Location = { AL["Silithus"], 1377 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "20";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Reputation"]..": "..BF["Cenarion Circle"], FACTION, 609 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Kurinnaxx"], NPC, 15348 };
		{ GREY..INDENT..AL["Lieutenant General Andorov"], NPC, 15471 };
		{ GREY..INDENT..AL["Four Kaldorei Elites"], NPC, 15473 };
		{ GREY.."2) "..AL["General Rajaxx"], NPC, 15341 };
		{ GREY..INDENT..AL["Captain Qeez"], NPC, 15391 };
		{ GREY..INDENT..AL["Captain Tuubid"], NPC, 15392 };
		{ GREY..INDENT..AL["Captain Drenn"], NPC, 15389 };
		{ GREY..INDENT..AL["Captain Xurrem"], NPC, 15390 };
		{ GREY..INDENT..AL["Major Yeggeth"], NPC, 15386 };
		{ GREY..INDENT..AL["Major Pakkon"], NPC, 15388 };
		{ GREY..INDENT..AL["Colonel Zerran"], NPC, 15385 };
		{ GREY.."3) "..AL["Moam"].." ("..AL["Optional"]..")", NPC, 15340 };
		{ GREY.."4) "..AL["Buru the Gorger"].." ("..AL["Optional"]..")", NPC, 15370 };
		{ GREY.."5) "..AL["Ayamiss the Hunter"].." ("..AL["Optional"]..")", NPC, 15369 };
		{ GREY.."6) "..AL["Ossirian the Unscarred"], NPC, 15339 };
		{ GREN.."1') "..AL["Safe Room"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Class Books"] };
		{ GREY..INDENT..AL["AQ Enchants"] };
		{ GREY..INDENT..AL["Ruins of Ahn'Qiraj Sets"] };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Nature"] };
	};

--************************************************
-- Eastern Kingdoms Instances
--************************************************
	DragonmawRetreat = {
		ZoneName = { AL["Dragonmaw Retreat"], -1 };
		Acronym = "DMR";
		Location = { AL["Wetlands"], -1 };
		LevelRange = "25-35";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Exit"] };
		{ GREY.."1) "..AL["Gowlfang"] };
		{ GREY.."2) "..AL["Cavernweb Broodmother"] };
		{ GREY.."3) "..AL["Web Master Torkon"] };
		{ GREY.."4) "..AL["Garlok Flamekeeper"] };
		{ GREY.."5) "..AL["Halgan Redbrand"] };
		{ GREY.."6) "..AL["Slagfist Destroyer"] };
		{ GREY.."7) "..AL["Overlord Blackheart"] };
		{ GREY.."8) "..AL["Elder Hollowblood"] };
		{ GREY.."9) "..AL["Searistrasz"] };
		{ GREY.."10) "..AL["Zuluhed the Whacked"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	StormwroughtRuins = {
		ZoneName = { AL["Stormwrought Ruins"]};
		Acronym = "SWR";
		Location = { AL["Balor"]};
		LevelRange = "32-44";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Entrance"].." ("..AL["Back"]..")" };
		{ GREY.."1) "..AL["Oronok Torn-Heart"] };
		{ GREY.."2) "..AL["Dagar the Glutton"] };
		{ GREY.."3) "..AL["Duke Balor the IV"] };
		{ GREY.."4) "..AL["Librarian Theodorus"] };
		{ GREY.."5) "..AL["Chieftain Stormsong"] };
		{ GREY.."6) "..AL["Deathlord Tidebane"] };
		{ GREY.."7) "..AL["Subjugator Halthas Shadecrest"] };
		{ GREY.."8) "..AL["Mycellakos"] };
		{ GREY.."9) "..AL["Eldermaw the Primordial"] };
		{ GREY.."10) "..AL["Lady Drazare"] };
		{ GREY.."11) "..AL["Remains of the Innocent"] };
		{ GREY.."12) "..AL["Mergothid"] };
		{ GREY..INDENT..AL["Ighal'for"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	BlackrockDepths = {
		ZoneName = { AL["Blackrock Depths"], 1584 };
		Acronym = "BRD";
		Location = { AL["Blackrock Mountain"], 25 };
		LevelRange = "52-60";
		MinLevel = "42";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["Shadowforge Key"], ITEM, 11000 };
		{ ORNG..AL["Key"]..": "..AL["Prison Cell Key"], ITEM, 11140 };
		{ ORNG..AL["Key"]..": "..AL["Banner of Provocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 21986 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Lord Roccor"], NPC, 9025 };
		{ GREY.."2) "..AL["Kharan Mighthammer"], NPC, 9021 };
		{ GREY.."3) "..AL["Commander Gor'shak"], NPC, 9020 };
		{ GREY.."4) "..AL["Marshal Windsor"], NPC, 9023 };
		{ GREY.."5) "..AL["High Interrogator Gerstahn"], NPC, 9018 };
		{ GREY.."6) "..AL["Ring of Law"] };
		{ GREY..INDENT..AL["Anub'shiah"].." ("..AL["Random"]..")", NPC, 9031 };
		{ GREY..INDENT..AL["Eviscerator"].." ("..AL["Random"]..")", NPC, 9029 };
		{ GREY..INDENT..AL["Gorosh the Dervish"].." ("..AL["Random"]..")", NPC, 9027 };
		{ GREY..INDENT..AL["Grizzle"].." ("..AL["Random"]..")", NPC, 9028 };
		{ GREY..INDENT..AL["Hedrum the Creeper"].." ("..AL["Random"]..")", NPC, 9032 };
		{ GREY..INDENT..AL["Ok'thor the Breaker"].." ("..AL["Random"]..")", NPC, 9030 };
		{ GREY..INDENT..AL["Theldren"].." ("..AL["Summon"]..")", NPC, 16059 };
		{ GREY..INDENT..AL["Lefty"].." (|cfffff468"..BC["Rogue"]..GREY..")", NPC, 16049 };
		{ GREY..INDENT..AL["Malgen Longspear"].." (|cffaad372"..BC["Hunter"]..GREY..")", NPC, 16052 };
		{ GREY..INDENT..AL["Gnashjaw"].." (|cffaad372"..AL["Pet"]..GREY..")", NPC, 16095 };
		{ GREY..INDENT..AL["Korv"].." (|cff2773ff"..BC["Shaman"]..GREY..")", NPC, 16050 };
		{ GREY..INDENT..AL["Rezznik"].." (|cffc69b6d"..AL["Engineer"]..GREY..")", NPC, 16050 };
		{ GREY..INDENT..AL["Rotfang"].." (|cfffff468"..BC["Rogue"]..GREY..")", NPC, 16050 };
		{ GREY..INDENT..AL["Snokh Blackspine"].." (|cff68ccef"..BC["Mage"]..GREY..")", NPC, 16050 };
		{ GREY..INDENT..AL["Va'jashni"].." (|cffffffff"..BC["Priest"]..GREY..")", NPC, 16055 };
		{ GREY..INDENT..AL["Volida"].." (|cff68ccef"..BC["Mage"]..GREY..")", NPC, 16055 };
		{ GREY..INDENT..AL["Houndmaster Grebmar"].." ("..AL["Lower"]..")", NPC, 9319 };
		{ GREY..INDENT..AL["Elder Morndeep"].." ("..AL["Lunar Festival"]..")", NPC, 15549 };
		{ GREY..INDENT..AL["High Justice Grimstone"], NPC, 10096 };
		{ GREY.."7) "..AL["Monument of Franclorn Forgewright"], OBJECT, 164689 };
		{ GREY..INDENT..AL["Pyromancer Loregrain"].." ("..AL["Rare"]..")", NPC, 9024 };
		{ GREY.."8) "..AL["The Vault"] };
		{ GREY..INDENT..AL["Warder Stilgiss"].." ("..AL["Rare"]..")", NPC, 9041 };
		{ GREY..INDENT..AL["Verek"].." ("..AL["Rare"]..")", NPC, 9042 };
		{ GREY..INDENT..AL["Watchman Doomgrip"], NPC, 9476 };
		{ GREY.."9) "..AL["Fineous Darkvire"], NPC, 9056 };
		{ GREY.."10) "..AL["Lord Incendius"], NPC, 9017 };
		{ GREY..INDENT..AL["The Black Anvil"] };
		{ GREY.."11) "..AL["Bael'Gar"], NPC, 9016 };
		{ GREY.."12) "..AL["Shadowforge Lock"] };
		{ GREY.."13) "..AL["General Angerforge"], NPC, 9033 };
		{ GREY.."14) "..AL["Golem Lord Argelmach"], NPC, 8983 };
		{ GREY..INDENT..AL["Field Repair Bot 74A"], NPC, 14337 };
		{ GREY..INDENT..AL["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."15) "..AL["The Grim Guzzler"] };
		{ GREY..INDENT..AL["Hurley Blackbreath"], NPC, 9537 };
		{ GREY..INDENT..AL["Lokhtos Darkbargainer"], NPC, 12944 };
		{ GREY..INDENT..AL["Mistress Nagmara"], NPC, 9500 };
		{ GREY..INDENT..AL["Phalanx"], NPC, 9502 };
		{ GREY..INDENT..AL["Plugger Spazzring"], NPC, 9499 };
		{ GREY..INDENT..AL["Private Rocknot"], NPC, 9503 };
		{ GREY..INDENT..AL["Ribbly Screwspigot"], NPC, 9543 };
		{ GREY.."16) "..AL["Ambassador Flamelash"], NPC, 9156 };
		{ GREY.."17) "..AL["Panzor the Invincible"].." ("..AL["Rare"]..")", NPC, 8923 };
		{ GREY..INDENT..AL["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."18) "..AL["Summoner's Tomb"] };
		{ GREY..INDENT..AL["Chest of The Seven"], OBJECT, 169243 };
		{ GREY.."19) "..AL["The Lyceum"] };
		{ GREY.."20) "..AL["Magmus"], NPC, 9938 };
		{ GREY.."21) "..AL["Emperor Dagran Thaurissan"], NPC, 9019 };
		{ GREY..INDENT..AL["Princess Moira Bronzebeard"], NPC, 8929 };
		{ GREY..INDENT..AL["High Priestess of Thaurissan"], NPC, 10076 };
		{ GREY.."22) "..AL["The Black Forge"] };
		{ GREY.."23) "..AL["Molten Core"], ZONE, 2717 };
		{ GREY..INDENT..AL["Core Fragment"], OBJECT, 179553 };
		{ GREY.."24) "..AL["Overmaster Pyron"], NPC, 9026 };
		{ GREY.."25) "..AL["Blacksmithing Plans"], OBJECT, 173232 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["The Gladiator"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
	};
	BlackrockSpireLower = {
		ZoneName = { AL["Lower Blackrock Spire"], 1583 };
		Acronym = "LBRS";
		Location = { AL["Blackrock Mountain"], 25 };
		LevelRange = "55-60";
		MinLevel = "55";
		PlayerLimit = "10";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["Brazier of Invocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Upper Blackrock Spire"].." (UBRS)", ZONE, 1583 };
		{ BLUE.."C-F) "..AL["Connections"] };
		{ GREY.."1) "..AL["Vaelan"].." ("..AL["Upper"]..")", NPC, 10296 };
		{ GREY.."2) "..AL["Warosh"].." ("..AL["Wanders"]..")", NPC, 10799 };
		{ GREY..INDENT..AL["Elder Stonefort"].." ("..AL["Lunar Festival"]..")", NPC, 15560 };
		{ GREY.."3) "..AL["Roughshod Pike"], OBJECT, 175886 };
		{ GREY.."4) "..AL["Spirestone Butcher"].." ("..AL["Rare"]..")", NPC, 9219 };
		{ GREY.."5) "..AL["Highlord Omokk"], NPC, 9196 };
		{ GREY.."6) "..AL["Spirestone Battle Lord"].." ("..AL["Rare"]..")", NPC, 9218 };
		{ GREY..INDENT..AL["Spirestone Lord Magus"].." ("..AL["Rare"]..")", NPC, 9217 };
		{ GREY.."7) "..AL["Shadow Hunter Vosh'gajin"], NPC, 9236 };
		{ GREY..INDENT..AL["Fifth Mosh'aru Tablet"], OBJECT, 175949 };
		{ GREY.."8) "..AL["Bijou"], NPC, 10257 };
		{ GREY.."9) "..AL["War Master Voone"], NPC, 9237 };
		{ GREY..INDENT..AL["Mor Grayhoof"].." ("..AL["Summon"]..")", NPC, 16080 };
		{ GREY..INDENT..AL["Sixth Mosh'aru Tablet"], OBJECT, 175950 };
		{ GREY.."10) "..AL["Bijou's Belongings"], OBJECT, 175334 };
		{ GREY.."11) "..AL["Human Remains"].." ("..AL["Lower"]..")", OBJECT, 176090 };
		{ GREY..INDENT..AL["Unfired Plate Gauntlets"].." ("..AL["Lower"]..")", OBJECT, 176089 };
		{ GREY.."12) "..AL["Bannok Grimaxe"].." ("..AL["Rare"]..")", NPC, 9596 };
		{ GREY.."13) "..AL["Mother Smolderweb"], NPC, 10596 };
		{ GREY.."14) "..AL["Crystal Fang"].." ("..AL["Rare"]..")", NPC, 10376 };
		{ GREY.."15) "..AL["Urok's Tribute Pile"], OBJECT, 175621 };
		{ GREY..INDENT..AL["Urok Doomhowl"].." ("..AL["Summon"]..")", NPC, 10584 };
		{ GREY.."16) "..AL["Quartermaster Zigris"], NPC, 9736 };
		{ GREY.."17) "..AL["Halycon"], NPC, 10220 };
		{ GREY..INDENT..AL["Gizrul the Slavener"], NPC, 10268 };
		{ GREY.."18) "..AL["Ghok Bashguud"].." ("..AL["Rare"]..")", NPC, 9718 };
		{ GREY.."19) "..AL["Overlord Wyrmthalak"], NPC, 9568 };
		{ GREN.."1') "..AL["Burning Felguard"].." ("..AL["Rare"]..", "..AL["Summon"]..")", NPC, 10263 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Spider's Kiss"] };
		{ GREY..INDENT..AL["Set: "]..AL["Tier 0/0.5 Sets"] };
	};
	BlackrockSpireUpper = {
		ZoneName = { AL["Upper Blackrock Spire"], 1583 };
		Acronym = "UBRS";
		Location = { AL["Blackrock Mountain"], 25 };
		LevelRange = "55-60";
		MinLevel = "55";
		PlayerLimit = "10";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["Seal of Ascension"], ITEM, 12344 };
		{ ORNG..AL["Key"]..": "..AL["Brazier of Invocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Lower Blackrock Spire"].." (LBRS)", ZONE, 1583 };
		{ BLUE.."C-E) "..AL["Connections"] };
		{ GREY.."1) "..AL["Pyroguard Emberseer"], NPC, 9816 };
		{ GREY.."2) "..AL["Solakar Flamewreath"], NPC, 10264 };
		{ GREY..INDENT..AL["Father Flame"], OBJECT, 175245 };
		{ GREY.."3) "..AL["Darkstone Tablet"], OBJECT, 175385 };
		{ GREY..INDENT..AL["Doomrigger's Coffer"], OBJECT, 175382 };
		{ GREY.."4) "..AL["Jed Runewatcher"].." ("..AL["Rare"]..")", NPC, 10509 };
		{ GREY.."5) "..AL["Goraluk Anvilcrack"].." ("..AL["Rare"]..")", NPC, 10899 };
		{ GREY.."6) "..AL["Warchief Rend Blackhand"], NPC, 10429 };
		{ GREY..INDENT..AL["Gyth"], NPC, 10339 };
		{ GREY.."7) "..AL["Awbee"], NPC, 10740 };
		{ GREY.."8) "..AL["The Beast"], NPC, 10430 };
		{ GREY..INDENT..AL["Lord Valthalak"].." ("..AL["Summon"]..")", NPC, 16042 };
		{ GREY..INDENT..AL["Finkle Einhorn"], NPC, 10776 };
		{ GREY.."9) "..AL["General Drakkisath"], NPC, 10363 };
		{ GREY..INDENT..AL["Drakkisath's Brand"], OBJECT, 179880 };
		{ GREY.."10) "..AL["Blackwing Lair"].." (BWL)", ZONE, 2677 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
		{ GREY..INDENT..AL["Tier 0/0.5 Sets"] };
	};
	BlackwingLair = {
		ZoneName = { AL["Blackwing Lair"], 2677 };
		Acronym = "BWL";
		Location = { AL["Blackrock Spire"], 1583 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Attunement Required"] };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ BLUE.."C) "..AL["Connection"] };
		{ GREY.."1) "..AL["Razorgore the Untamed"], NPC, 12435 };
		{ GREY.."2) "..AL["Vaelastrasz the Corrupt"], NPC, 13020 };
		{ GREY.."3) "..AL["Broodlord Lashlayer"], NPC, 12017 };
		{ GREY.."4) "..AL["Firemaw"], NPC, 11983 };
		{ GREY.."5) "..AL["Master Elemental Shaper Krixix"], NPC, 14401 };
		{ GREY.."6) "..AL["Ebonroc"], NPC, 14601 };
		{ GREY.."7) "..AL["Flamegor"], NPC, 11981 };
		{ GREY.."8) "..AL["Chromaggus"], NPC, 14020 };
		{ GREY.."9) "..AL["Nefarian"], NPC, 11583 };
		{ GREY.."10) "..AL["Ezzel Darkbrewer"], NPC, 10184 };
		{ GREN.."1') "..AL["Alchemy Lab"] };
		{ GREN.."2') "..AL["Draconic for Dummies"], OBJECT, 180666 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Tier 2 Sets"] };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Fire"] };
	};
	Gnomeregan = {
		ZoneName = { AL["Gnomeregan"], 133 };
		Acronym = "Gnome";
		Location = { AL["Dun Morogh"], 1 };
		LevelRange = "29-38";
		MinLevel = "19";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["Workshop Key"].." ("..AL["Back"]..")", ITEM, 6893 };
		{ BLUE.."A) "..AL["Entrance"].." ("..AL["Front"]..")" };
		{ BLUE.."B) "..AL["Entrance"].." ("..AL["Back1"]..")" };
		{ GREY.."1) "..AL["Blastmaster Emi Shortfuse"], NPC, 7998 };
		{ GREY..INDENT..AL["Grubbis"], NPC, 7361 };
		{ GREY..INDENT..AL["Chomper"], NPC, 6215 };
		{ GREY.."2) "..AL["Clean Room"] };
		{ GREY..INDENT..AL["Tink Sprocketwhistle"], NPC, 9676 };
		{ GREY..INDENT..AL["The Sparklematic 5200"], OBJECT, 142487 };
		{ GREY..INDENT..AL["Mail Box"] };
		{ GREY.."3) "..AL["Kernobee"], NPC, 7850 };
		{ GREY..INDENT..AL["Alarm-a-bomb 2600"], NPC, 7897 };
		{ GREY..INDENT..AL["Matrix Punchograph 3005-B"], OBJECT, 142475 };
		{ GREY.."4) "..AL["Viscous Fallout"], NPC, 7079 };
		{ GREY.."5) "..AL["Electrocutioner 6000"], NPC, 6235 };
		{ GREY..INDENT..AL["Matrix Punchograph 3005-C"], OBJECT, 142476 };
		{ GREY.."6) "..AL["Crowd Pummeler 9-60"].." ("..AL["Upper"]..")", NPC, 6229 };
		{ GREY..INDENT..AL["Matrix Punchograph 3005-D"], OBJECT, 142696 };
		{ GREY.."7) "..AL["Dark Iron Ambassador"].." ("..AL["Rare"]..")", NPC, 6228 };
		{ GREY.."8) "..AL["Mekgineer Thermaplugg"], NPC, 7800 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	MoltenCore = {
		ZoneName = { AL["Molten Core"], 2717 };
		Acronym = "MC";
		Location = { AL["Blackrock Depths"], 1584 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Attunement Required"] };
		{ ORNG..AL["Reputation"]..": "..BF["Hydraxian Waterlords"], FACTION, 749 };
		{ ORNG..AL["Key"]..": "..AL["Aqual Quintessence"].." ("..AL["Boss"]..")", ITEM, 17333 };
		{ ORNG..AL["Key"]..": "..AL["Eternal Quintessence"].." ("..AL["Boss"]..")", ITEM, 22754 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Incindis"], NPC, -1 };
		{ GREY.."2) "..AL["Lucifron"], NPC, 12118 };
		{ GREY.."3) "..AL["Magmadar"], NPC, 11982 };
		-- { GREY.."3) "..AL["Gehennas"], NPC, 12259 };
		{ GREY.."4) "..AL["Garr"], NPC, 12057 };
		{ GREY.."5) "..AL["Baron Geddon"], NPC, 12056 };
		{ GREY.."6) "..AL["Shazzrah"], NPC, 12264 };
		{ GREY.."7) "..AL["Sulfuron Harbinger"], NPC, 12098 };
		{ GREY.."8) "..AL["Golemagg the Incinerator"], NPC, 11988 };
		{ GREY.."9) "..AL["Basalthar & Smoldaris"], NPC, -1 };
		{ GREY.."10) "..AL["Sorcerer-Thane Thaurissan"], NPC, -1 };
		{ GREY.."11) "..AL["Majordomo Executus"], NPC, 12018 };
		{ GREY.."12) "..AL["Ragnaros"], NPC, 11502 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Random Boss Loot"] };
		{ GREY..INDENT..AL["Tier 1 Sets"] };
		{ GREY..INDENT..AL["Tier 2 Sets"] };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Fire"] };
	};
	Naxxramas = {
		ZoneName = { AL["Naxxramas"], 3456 };
		Acronym = "Naxx";
		Location = { AL["Eastern Plaguelands"], 139 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Attunement Required"] };
		{ ORNG..AL["Reputation"]..": "..BF["Argent Dawn"], FACTION, 529 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE..INDENT..AL["Archmage Tarsis Kir-Moldir"], NPC, 16381 };
		{ BLUE..INDENT..AL["Mr. Bigglesworth"].." ("..AL["Wanders"]..")", NPC, 16998 };
		{ GREY..AL["Abomination Wing"] };
		{ GREY..INDENT.."1) "..AL["Patchwerk"], NPC, 16028 };
		{ GREY..INDENT.."2) "..AL["Grobbulus"], NPC, 15931 };
		{ GREY..INDENT.."3) "..AL["Gluth"], NPC, 15932 };
		{ GREY..INDENT.."4) "..AL["Thaddius"], NPC, 15928 };
		{ ORNG..AL["Spider Wing"] };
		{ ORNG..INDENT.."1) "..AL["Anub'Rekhan"], NPC, 15956 };
		{ ORNG..INDENT.."2) "..AL["Grand Widow Faerlina"], NPC, 15953 };
		{ ORNG..INDENT.."3) "..AL["Maexxna"], NPC, 15952 };
		{ PURP..AL["Plague Wing"] };
		{ PURP..INDENT.."1) "..AL["Noth the Plaguebringer"], NPC, 15954 };
		{ PURP..INDENT.."2) "..AL["Heigan the Unclean"], NPC, 15936 };
		{ PURP..INDENT.."3) "..AL["Loatheb"], NPC, 16011 };
		{ _RED..AL["Deathknight Wing"] };
		{ _RED..INDENT.."1) "..AL["Instructor Razuvious"], NPC, 16061 };
		{ _RED..INDENT.."2) "..AL["Gothik the Harvester"], NPC, 16060 };
		{ _RED..INDENT.."3) "..AL["The Four Horsemen"] };
		{ _RED..INDENT..INDENT..AL["Thane Korth'azz"], NPC, 16064 };
		{ _RED..INDENT..INDENT..AL["Lady Blaumeux"], NPC, 16065 };
		{ _RED..INDENT..INDENT..AL["Highlord Mograine"], NPC, 16062 };
		{ _RED..INDENT..INDENT..AL["Sir Zeliek"], NPC, 16063 };
		{ GREN..AL["Frostwyrm Lair"] };
		{ GREN..INDENT.."1) "..AL["Sapphiron"], NPC, 15989 };
		{ GREN..INDENT.."2) "..AL["Kel'Thuzad"], NPC, 15990 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Tier 3 Sets"] };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Nature"]..", "..AL["Fire"]..", "..AL["Arcane"]..", "..AL["Shadow"]..", "..AL["Frost"]};
	};
	SMLibrary = {
		ZoneName = { AL["Scarlet Monastery"]..": "..AL["Library"], 796 };
		Acronym = "SM Lib";
		Location = { AL["Tirisfal Glades"], 85 };
		LevelRange = "29-39";
		MinLevel = "21";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Houndmaster Loksey"], NPC, 3974 };
		{ GREY.."2) "..AL["Arcanist Doan"], NPC, 6487 };
		{ GREN.."1') "..AL["Doan's Strongbox"], OBJECT, 103821 };
		{ GREY.."3) ".."Brother Wystan", NPC, -1  };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Chain of the Scarlet Crusade"] };
	};
	SMArmory = {
		ZoneName = { AL["Scarlet Monastery"]..": "..AL["Armory"], 796 };
		Acronym = "SM Arm";
		Location = { AL["Tirisfal Glades"], 85 };
		LevelRange = "32-42";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["The Scarlet Key"], ITEM, 7146 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Herod"], NPC, 3975 };
		{ GREY.."2) ".."Armory Quartermaster Daghelm", NPC, -1 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Chain of the Scarlet Crusade"] };
	};
	SMCathedral = {
		ZoneName = { AL["Scarlet Monastery"]..": "..AL["Cathedral"], 796 };
		Acronym = "SM Cath";
		Location = { AL["Tirisfal Glades"], 85 };
		LevelRange = "35-45";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["The Scarlet Key"], ITEM, 7146 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["High Inquisitor Fairbanks"], NPC, 4542 };
		{ GREY.."2) "..AL["Scarlet Commander Mograine"], NPC, 3976 };
		{ GREY.."3) "..AL["High Inquisitor Whitemane"], NPC, 3977 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Chain of the Scarlet Crusade"] };
	};
	SMGraveyard = {
		ZoneName = { AL["Scarlet Monastery"]..": "..AL["Graveyard"], 796 };
		Acronym = "SM GY";
		Location = { AL["Tirisfal Glades"], 85 };
		LevelRange = "26-36";
		MinLevel = "25";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Interrogator Vishas"], NPC, 3983 };
		{ GREY..INDENT..AL["Vorrel Sengutz"], NPC, 3981 };
		{ GREY.."2) "..AL["Scorn"].." ("..AL["Scourge Invasion"]..")", NPC, 14693 };
		{ GREY.."3) "..AL["Bloodmage Thalnos"], NPC, 4543 };
		{ GREN.."1') "..AL["Ironspine"].." ("..AL["Rare"]..")", NPC, 6489 };
		{ GREN..INDENT..AL["Azshir the Sleepless"].." ("..AL["Rare"]..")", NPC, 6490 };
		{ GREN..INDENT..AL["Fallen Champion"].." ("..AL["Rare"]..")", NPC, 6488 };
		{ GREY.."4) ".."Duke Dreadmoore", NPC, -1 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Chain of the Scarlet Crusade"] };
	};
	Scholomance = {
		ZoneName = { AL["Scholomance"], 2057 };
		Acronym = "Scholo";
		Location = { AL["Western Plaguelands"], 28 };
		LevelRange = "58-60";
		MinLevel = "45";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["Argent Dawn"], FACTION, 529 };
		{ ORNG..AL["Key"]..": "..AL["Skeleton Key"], ITEM, 13704 };
		{ ORNG..AL["Key"]..": "..AL["Viewing Room Key"].." ("..AL["Viewing Room"]..")", ITEM, 13873 };
		{ ORNG..AL["Key"]..": "..AL["Blood of Innocents"].." ("..AL["Kirtonos the Herald"]..")", ITEM, 13523 };
		{ ORNG..AL["Key"]..": "..AL["Brazier of Invocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 22057 };
		{ ORNG..AL["Key"]..": "..AL["Divination Scryer"].." ("..AL["Death Knight Darkreaver"]..")", ITEM, 18746 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ BLUE.."C) "..AL["Connection"] };
		{ GREY.."1) "..AL["Blood Steward of Kirtonos"], NPC, 14861 };
		{ GREY..INDENT..AL["The Deed to Southshore"], OBJECT, 176486 };
		{ GREY.."2) "..AL["Kirtonos the Herald"].." ("..AL["Summon"]..")", NPC, 10506 };
		{ GREY.."3) "..AL["Jandice Barov"], NPC, 10503 };
		{ GREY..INDENT..AL["Journal of Jandice Barov"], OBJECT, 180794 };
		{ GREY.."4) "..AL["The Deed to Tarren Mill"], OBJECT, 176487 };
		{ GREY..INDENT..AL["Lord Blackwood"].." ("..AL["Scourge Invasion"]..")", NPC, 14695 };
		{ GREY.."5) "..AL["Rattlegore"].." ("..AL["Lower"]..")", NPC, 11622 };
		{ GREY..INDENT..AL["Death Knight Darkreaver"].." ("..AL["Summon"]..")", NPC, 14516 };
		{ GREY.."6) "..AL["Marduk Blackpool"], NPC, 10433 };
		{ GREY..INDENT..AL["Vectus"], NPC, 10432 };
		{ GREY.."7) "..AL["Ras Frostwhisper"], NPC, 10508 };
		{ GREY..INDENT..AL["The Deed to Brill"], OBJECT, 176484 };
		{ GREY..INDENT..AL["Kormok"].." ("..AL["Summon"]..")", NPC, 16118 };
		{ GREY.."8) "..AL["Instructor Malicia"], NPC, 10505 };
		{ GREY.."9) "..AL["Doctor Theolen Krastinov"], NPC, 11261 };
		{ GREY.."10) "..AL["Lorekeeper Polkelt"], NPC, 10901 };
		{ GREY.."11) "..AL["The Ravenian"], NPC, 10507 };
		{ GREY.."12) "..AL["Lord Alexei Barov"], NPC, 10504 };
		{ GREY..INDENT..AL["The Deed to Caer Darrow"], OBJECT, 176485 };
		{ GREY.."13) "..AL["Lady Illucia Barov"], NPC, 10502 };
		{ GREY.."14) "..AL["Darkmaster Gandling"], NPC, 1853 };
		{ GREN.."1') "..AL["Torch Lever"] };
		{ GREN.."2') "..AL["Old Treasure Chest"], OBJECT, 176944 };
		{ GREN.."3') "..AL["Alchemy Lab"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Necropile Raiment"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Cadaverous Garb"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Bloodmail Regalia"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Deathbone Guardian"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
		{ GREY..INDENT..AL["Tier 0/0.5 Sets"] };
	};
	ShadowfangKeep = {
		ZoneName = { AL["Shadowfang Keep"], 209 };
		Acronym = "SFK";
		Location = { AL["Silverpine Forest"], 130 };
		LevelRange = "22-30";
		MinLevel = "14";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Rethilgore"], NPC, 3914 };
		{ GREY..INDENT..AL["Sorcerer Ashcrombe"], NPC, 3850 };
		{ GREY..INDENT..AL["Deathstalker Adamant"], NPC, 3849 };
		{ GREY.."2) "..AL["Deathstalker Vincent"], NPC, 4444 };
		{ GREY.."3) "..AL["Fel Steed"], NPC, 3864 };
		{ GREY..INDENT..AL["Jordan's Hammer"], OBJECT, 91138 };
		{ GREY.."4) "..AL["Razorclaw the Butcher"], NPC, 3886 };
		{ GREY.."5) "..AL["Baron Silverlaine"], NPC, 3887 };
		{ GREY.."6) "..AL["Commander Springvale"], NPC, 4278 };
		{ GREY.."7) "..AL["Sever"].." ("..AL["Scourge Invasion"]..")", NPC, 4279 };
		{ GREY.."8) "..AL["Odo the Blindwatcher"], NPC, 4279 };
		{ GREY.."9) "..AL["Deathsworn Captain"].." ("..AL["Rare"]..")", NPC, 3872 };
		{ GREY.."10) "..AL["Fenrus the Devourer"], NPC, 4274 };
		{ GREY..INDENT..AL["Arugal's Voidwalker"], NPC, 4627 };
		{ GREY..INDENT..AL["The Book of Ur"], OBJECT, 36738 };
		{ GREY.."11) "..AL["Wolf Master Nandos"], NPC, 3927 };
		{ GREY.."12) "..AL["Archmage Arugal"], NPC, 4275 };
		{ GREY.."13) ".."Prelate Ironmane", NPC, -1 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	Stratholme = {
		ZoneName = { AL["Stratholme"], 2017 };
		Acronym = "Strat";
		Location = { AL["Eastern Plaguelands"], 139 };
		LevelRange = "58-60";
		MinLevel = "45";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["Argent Dawn"], FACTION, 529 };
		{ ORNG..AL["Key"]..": "..AL["The Scarlet Key"].." ("..AL["Living Side"]..")", ITEM, 7146 };
		{ ORNG..AL["Key"]..": "..AL["Key to the City"].." ("..AL["Undead Side"]..")", ITEM, 12382 };
		{ ORNG..AL["Key"]..": "..AL["Various Postbox Keys"].." ("..AL["Postmaster Malown"]..")" };
		{ ORNG..AL["Key"]..": "..AL["Brazier of Invocation"].." ("..AL["Тier 0.5 Summon"]..")", ITEM, 22057 };
		{ BLUE.."A) "..AL["Entrance"].." ("..AL["Front"]..")" };
		{ BLUE.."B) "..AL["Entrance"].." ("..AL["Side"]..")" };
		{ GREY.."1) "..AL["Skul"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 10393 };
		{ GREY..INDENT..AL["Stratholme Courier"], NPC, 11082 };
		{ GREY..INDENT..AL["Fras Siabi"], NPC, 11058 };
		{ GREY.."2) "..AL["Atiesh"].." ("..AL["Summon"]..")", NPC, 16387 };
		{ GREY..INDENT..AL["Balzaphon"].." ("..AL["Scourge Invasion"]..")", NPC, 14684 };
		{ GREY.."3) "..AL["Hearthsinger Forresten"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 10558 };
		{ GREY.."4) "..AL["The Unforgiven"], NPC, 10516 };
		{ GREY.."5) "..AL["Elder Farwhisper"].." ("..AL["Lunar Festival"]..")", NPC, 15607 };
		{ GREY.."6) "..AL["Timmy the Cruel"], NPC, 10808 };
		{ GREY.."7) "..AL["Malor the Zealous"], NPC, 11032 };
		{ GREY..INDENT..AL["Malor's Strongbox"], OBJECT, 176112 };
		{ GREY.."8) "..AL["Crimson Hammersmith"].." ("..AL["Summon"]..")", NPC, 11120 };
		{ GREY..INDENT..AL["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."9) "..AL["Cannon Master Willey"], NPC, 10997 };
		{ GREY.."10) "..AL["Archivist Galford"], NPC, 10811 };
		{ GREY.."11) "..AL["Grand Crusader Dathrohan"], NPC, 10812 };
		{ GREY..INDENT..AL["Balnazzar"], NPC, 10813 };
		{ GREY..INDENT..AL["Sothos"].." & "..AL["Jarien"].." ("..AL["Summon"]..")", NPC, 16102 };
		{ GREY.."12) "..AL["Magistrate Barthilas"].." ("..AL["Varies"]..")", NPC, 10435 };
		{ GREY.."13) "..AL["Aurius"], NPC, 10917 };
		{ GREY.."14) "..AL["Stonespine"].." ("..AL["Rare"]..", "..AL["Wanders"]..")", NPC, 10809 };
		{ GREY.."15) "..AL["Baroness Anastari"], NPC, 10436 };
		{ GREY..INDENT..AL["Black Guard Swordsmith"].." ("..AL["Summon"]..")", NPC, 11121 };
		{ GREY..INDENT..AL["Blacksmithing Plans"], OBJECT, 173232 };
		{ GREY.."16) "..AL["Nerub'enkan"], NPC, 10437 };
		{ GREY.."17) "..AL["Maleki the Pallid"], NPC, 10438 };
		{ GREY.."18) "..AL["Ramstein the Gorger"], NPC, 10439 };
		{ GREY.."19) "..AL["Baron Rivendare"], NPC, 10440 };
		{ GREY..INDENT..AL["Ysida Harmon"], NPC, 16031 };
		{ GREN.."1') "..AL["Crusaders' Square Postbox"], OBJECT, 176349 };
		{ GREN.."2') "..AL["Market Row Postbox"], OBJECT, 176346 };
		{ GREN.."3') "..AL["Festival Lane Postbox"], OBJECT, 176350 };
		{ GREN.."4') "..AL["Elders' Square Postbox"], OBJECT, 176351 };
		{ GREN.."5') "..AL["King's Square Postbox"], OBJECT, 176352 };
		{ GREN.."6') "..AL["Fras Siabi's Postbox"], OBJECT, 176353 };
		{ GREN..INDENT..AL["Third Postbox Opened"]..": "..AL["Postmaster Malown"], NPC, 11143 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["The Postmaster"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Ironweave Battlesuit"] };
		{ GREY..INDENT..AL["Tier 0/0.5 Sets"] };
	};
	TheDeadmines = {
		ZoneName = { AL["The Deadmines"], 1581 };
		Acronym = "DM";
		Location = { AL["Westfall"], 40 };
		LevelRange = "17-24";
		MinLevel = "10";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Exit"] };
		{ GREY.."1) "..AL["Jared Voss"], NPC, -1};
		{ GREY.."2) "..AL["Rhahk'Zor"], NPC, 644 };
		{ GREY.."3) "..AL["Miner Johnson"].." ("..AL["Rare"]..")", NPC, 3586 };
		{ GREY.."4) "..AL["Sneed"], NPC, 643 };
		{ GREY..INDENT..AL["Sneed's Shredder"], NPC, 642 };
		{ GREY.."5) "..AL["Gilnid"], NPC, 1763 };
		{ GREY.."6) "..AL["Masterpiece Harvester"], NPC, -1};
		--{ GREY.."7) "..AL["Defias Gunpowder"], OBJECT, 17155 };
		{ GREY.."7) "..AL["Mr. Smite"], NPC, 646 };
		{ GREY.."8) "..AL["Cookie"], NPC, 645 };
		{ GREY.."9) "..AL["Captain Greenskin"], NPC, 647 };
		{ GREY.."10) "..AL["Edwin VanCleef"], NPC, 639 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Defias Leather"] };
	};
	TheStockade = {
		ZoneName = { AL["The Stockade"], 717 };
		Acronym = "Stocks";
		Location = { AL["Stormwind City"], 1519 };
		LevelRange = "24-31";
		MinLevel = "15";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["Targorr the Dread"].." ("..AL["Varies"]..")", NPC, 1696 };
		{ GREY.."2) "..AL["Kam Deepfury"], NPC, 1666 };
		{ GREY.."3) "..AL["Hamhock"], NPC, 1717 };
		{ GREY.."4) "..AL["Bazil Thredd"], NPC, 1716 };
		{ GREY.."5) "..AL["Dextren Ward"], NPC, 1663 };
		{ GREY.."6) "..AL["Bruegal Ironknuckle"].." ("..AL["Rare"]..")", NPC, 1720 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	TheSunkenTemple = {
		ZoneName = { AL["Sunken Temple"], 1417 };
		Acronym = "ST";
		Location = { AL["Swamp of Sorrows"], 8 };
		LevelRange = "50-60";
		MinLevel = "35";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["AKA"]..": "..AL["The Temple of Atal'Hakkar"] };
		{ ORNG..AL["Key"]..": "..AL["Yeh'kinya's Scroll"].." ("..AL["Avatar of Hakkar"]..")", ITEM, 10818 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Connection"] };
		{ BLUE.."C) "..AL["Balcony Minibosses"].." ("..AL["Upper"]..")" };
		{ BLUE..INDENT..AL["Gasher"], NPC, 5713 };
		{ BLUE..INDENT..AL["Loro"], NPC, 5714 };
		{ BLUE..INDENT..AL["Hukku"], NPC, 5715 };
		{ BLUE..INDENT..AL["Zolo"], NPC, 5712 };
		{ BLUE..INDENT..AL["Mijan"], NPC, 5717 };
		{ BLUE..INDENT..AL["Zul'Lor"], NPC, 5716 };
		{ GREY.."1) "..AL["Altar of Hakkar"], OBJECT, 148836 };
		{ GREY..INDENT..AL["Atal'alarion"], NPC, 8580 };
		{ GREY.."2) "..AL["Spawn of Hakkar"].." ("..AL["Wanders"]..")", NPC, 5708 };
		{ GREY.."3) "..AL["Avatar of Hakkar"], NPC, 8443 };
		{ GREY.."4) "..AL["Jammal'an the Prophet"], NPC, 5710 };
		{ GREY..INDENT..AL["Ogom the Wretched"], NPC, 5711 };
		{ GREY.."5) "..AL["Elder Starsong"].." ("..AL["Lunar Festival"]..")", NPC, 15593 };
		{ GREY.."6) "..AL["Dreamscythe"], NPC, 5721 };
		{ GREY..INDENT..AL["Weaver"], NPC, 5720 };
		{ GREY.."7) "..AL["Morphaz"], NPC, 5719 };
		{ GREY..INDENT..AL["Hazzas"], NPC, 5722 };
		{ GREY.."8) "..AL["Shade of Eranikus"], NPC, 5709 };
		{ GREY..INDENT..AL["Essence Font"], OBJECT, 148512 };
		{ GREY..INDENT..AL["Malfurion Stormrage"].." ("..AL["Summon"]..")", NPC, 15362 };
		{ GREN.."1'-6') "..AL["Statue Activation Order"] };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	Uldaman = {
		ZoneName = { AL["Uldaman"], 1337 };
		Acronym = "Ulda";
		Location = { AL["Badlands"], 3 };
		LevelRange = "41-51";
		MinLevel = "30";
		PlayerLimit = "5";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Key"]..": "..AL["Staff of Prehistoria"].." ("..AL["Ironaya"]..")", ITEM, 7733 };
		{ BLUE.."A) "..AL["Entrance"].." ("..AL["Front"]..")" };
		{ BLUE.."B) "..AL["Entrance"].." ("..AL["Back1"]..")" };
		{ GREY.."1) "..AL["Baelog"], NPC, 6906 };
		{ GREY..INDENT..AL["Eric \"The Swift\""], NPC, 6907 };
		{ GREY..INDENT..AL["Olaf"], NPC, 6908 };
		{ GREY..INDENT..AL["Baelog's Chest"], OBJECT, 123329 };
		{ GREY..INDENT..AL["Conspicuous Urn"], OBJECT, 125477 };
		{ GREY.."2) "..AL["Remains of a Paladin"], NPC, 6912 };
		{ GREY.."3) "..AL["Revelosh"], NPC, 6910 };
		{ GREY.."4) "..AL["Ironaya"], NPC, 7228 };
		{ GREY.."5) "..AL["Obsidian Sentinel"], NPC, 7023 };
		{ GREY.."6) "..AL["Annora"], NPC, 11073 };
		{ GREY.."7) "..AL["Ancient Stone Keeper"], NPC, 7206 };
		{ GREY.."8) "..AL["Galgann Firehammer"], NPC, 7291 };
		{ GREY..INDENT..AL["Tablet of Will"], OBJECT, 142088 };
		{ GREY..INDENT..AL["Shadowforge Cache"], OBJECT, 113757 };
		{ GREY.."9) "..AL["Grimlok"], NPC, 4854 };
		{ GREY.."10) "..AL["Archaedas"].." ("..AL["Lower"]..")", NPC, 2748 };
		{ GREY.."11) "..AL["The Discs of Norgannon"].." ("..AL["Lower"]..")", OBJECT, 131474 };
		{ GREY..INDENT..AL["Ancient Treasure"].." ("..AL["Lower"]..")", OBJECT, 141979 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	ZulGurub = {
		ZoneName = { AL["Zul'Gurub"], 19 };
		Acronym = "ZG";
		Location = { AL["Stranglethorn Vale"], 33 };
		LevelRange = "60+";
		MinLevel = "60";
		PlayerLimit = "20";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["Zandalar Tribe"], FACTION, 270 };
		{ ORNG..AL["Key"]..": "..AL["Gurubashi Mojo Madness"].." ("..AL["Edge of Madness"]..")", ITEM, 19931 };
		{ ORNG..AL["Key"]..": "..AL["Mudskunk Lure"].." ("..AL["Gahz'ranka"]..")", ITEM, 19974 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ GREY.."1) "..AL["High Priestess Jeklik"].." ("..AL["Bat"]..")", NPC, 14517 };
		{ GREY.."2) "..AL["High Priest Venoxis"].." ("..AL["Snake"]..")", NPC, 14507 };
		{ GREY.."3) "..AL["Zanza the Restless"], NPC, 15042 };
		{ GREY.."4) "..AL["High Priestess Mar'li"].." ("..AL["Spider"]..")", NPC, 14510 };
		{ GREY.."5) "..AL["Bloodlord Mandokir"].." ("..AL["Raptor"]..", "..AL["Optional"]..")", NPC, 11382 };
		{ GREY..INDENT..AL["Ohgan"], NPC, 14988 };
		{ GREY.."6) "..AL["Edge of Madness"].." ("..AL["Optional"]..")" };
		{ GREY..INDENT..AL["Gri'lek"].." ("..AL["Random"]..")", NPC, 15082 };
		{ GREY..INDENT..AL["Hazza'rah"].." ("..AL["Random"]..")", NPC, 15083 };
		{ GREY..INDENT..AL["Renataki"].." ("..AL["Random"]..")", NPC, 15084 };
		{ GREY..INDENT..AL["Wushoolay"].." ("..AL["Random"]..")", NPC, 15085 };
		{ GREY.."7) "..AL["Gahz'ranka"].." ("..AL["Optional"]..", "..AL["Summon"]..")", NPC, 15114 };
		{ GREY.."8) "..AL["High Priest Thekal"].." ("..AL["Tiger"]..")", NPC, 14509 };
		{ GREY..INDENT..AL["Zealot Zath"].." (|cfffff468"..BC["Rogue"]..GREY..")", NPC, 11348 };
		{ GREY..INDENT..AL["Zealot Lor'Khan"].." (|cff2773ff"..BC["Shaman"]..GREY..")", NPC, 11347 };
		{ GREY.."9) "..AL["High Priestess Arlokk"].." ("..AL["Panther"]..")", NPC, 14515 };
		{ GREY.."10) "..AL["Jin'do the Hexxer"].." ("..AL["Optional"]..")", NPC, 11380 };
		{ GREY.."11) "..AL["Hakkar"], NPC, 14834 };
		{ GREN.."1') "..AL["Muddy Churning Waters"], OBJECT, 180369 };
		{ GREN.."2') "..AL["Jinxed Hoodoo Pile"], OBJECT, 180228 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
		{ GREY..INDENT..AL["Random Boss Loot"] };
		{ GREY..INDENT..AL["Set: "]..BIS["Primal Blessing"] };
		{ GREY..INDENT..AL["Set: "]..BIS["The Twin Blades of Hakkari"] };
		{ GREY..INDENT..AL["Zul'Gurub Ring Sets"] };
		{ GREY..INDENT..AL["Zul'Gurub Sets"] };
		{ GREY..INDENT..AL["ZG Enchants"] };
		{ "" };
		{ ORNG..AL["Damage: "]..AL["Nature"] };
	};
	
--************************************************
-- Instance Entrance Maps
--************************************************

	BlackfathomDeepsEnt = {
		ZoneName = { AL["Blackfathom Deeps"].." ("..AL["Entrance"]..")", 719 };
		Location = { AL["Ashenvale"], 331 };
		Acronym = "BFD";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Blackfathom Deeps"], ZONE, 719 };
	};
	BlackrockMountainEnt = {
		ZoneName = { AL["Blackrock Mountain"].." ("..AL["Entrance"]..")", 25 };
		Location = { AL["Blackrock Mountain"], 51, 46 };
		Acronym = "BRM";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Searing Gorge"], ZONE, 51 };
		{ BLUE.."B) "..AL["Burning Steppes"], ZONE, 46 };
		{ BLUE.."C) "..AL["Blackrock Depths"].." (BRD)", ZONE, 1584 };
		{ BLUE..INDENT..AL["Molten Core"].." (MC) ("..AL["through "].."BRD)", ZONE, 2717 };
		{ BLUE.."D) "..AL["Lower Blackrock Spire"].." (LBRS)", ZONE, 1583 };
		{ BLUE..INDENT..AL["Upper Blackrock Spire"].." (UBRS)", ZONE, 1583 };
		{ BLUE..INDENT..AL["Blackwing Lair"].." (BWL) ("..AL["through "].."UBRS)", ZONE, 2677 };
		{ BLUE..INDENT..AL["Bodley"].." ("..AL["Ghost"]..")", NPC, 16033 };
		{ GREY.."1) "..AL["Overmaster Pyron"].." ("..AL["Wanders"]..")", NPC, 9026 };
		{ GREY.."2) "..AL["Lothos Riftwaker"].." (MC "..AL["Teleport"]..")", NPC, 14387 };
		{ GREY.."3) "..AL["Franclorn Forgewright"].." ("..AL["Ghost"]..")", NPC, 8888 };
		{ GREY.."4) "..AL["Meeting Stone"].." (BRD)" };
		{ GREY.."5) "..AL["Orb of Command"].." (BWL "..AL["Teleport"]..")", OBJECT, 179879 };
		{ GREY.."6) "..AL["Meeting Stone"].." (LBRS, UBRS)" };
		{ GREY.."7) "..AL["Scarshield Quartermaster"].." ("..AL["Rare"]..")", NPC, 9046 };
	};
	GnomereganEnt = {
		ZoneName = { AL["Gnomeregan"].." ("..AL["Entrance"]..")", 133 };
		Location = { AL["Dun Morogh"], 1 };
		Acronym = "Gnomer";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE..INDENT..AL["Meeting Stone"] };
		{ BLUE.."B) "..AL["Gnomeregan"].." ("..AL["Front"]..")", ZONE, 133 };
		{ BLUE.."C) "..AL["Gnomeregan"].." ("..AL["Back"]..")", ZONE, 133 };
		{ GREY.."1) "..AL["Elevator"] };
		{ GREY.."2) "..AL["Transpolyporter"] };
		{ GREY..INDENT..AL["Sprok"], NPC, 8320 };
		{ GREY.."3) "..AL["Matrix Punchograph 3005-A"], OBJECT, 142345 };
		{ GREY..INDENT..AL["Namdo Bizzfizzle"], NPC, 2683 };
		{ GREY.."4) "..AL["Techbot"], NPC, 6231 };
		{ "" };
		{ GREY..INDENT..AL["Trash Mobs"] };
	};
	MaraudonEnt = {
		ZoneName = { AL["Maraudon"].." ("..AL["Entrance"]..")", 2100 };
		Location = { AL["Desolace"], 405 };
		Acronym = "Mara";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE..INDENT..AL["The Nameless Prophet"], NPC, 13718 };
		{ BLUE.."B) "..AL["Maraudon"].." ("..AL["Purple"]..")", ZONE, 2100 };
		{ BLUE.."C) "..AL["Maraudon"].." ("..AL["Orange"]..")", ZONE, 2100 };
		{ BLUE.."D) "..AL["Maraudon"].." ("..AL["Portal"]..")", ZONE, 2100 };
		{ GREY.."1) "..AL["Kolk"], NPC, 13742 };
		{ GREY.."2) "..AL["Gelk"], NPC, 13741 };
		{ GREY.."3) "..AL["Magra"], NPC, 13740 };
		{ GREY.."4) "..AL["Cavindra"], NPC, 13697 };
		{ GREY.."5) "..AL["Cursed Centaur"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 11688 };
	};
	TheDeadminesEnt = {
		ZoneName = { AL["The Deadmines"].." ("..AL["Entrance"]..")", 1581 };
		Location = { AL["Westfall"], 40 };
		Acronym = "VC";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["The Deadmines"], ZONE, 1581 };
		{ GREY.."1) "..AL["Marisa du'Paige"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 599 };
		{ GREY.."2) "..AL["Brainwashed Noble"].." ("..AL["Rare"]..")", NPC, 596 };
		{ GREY.."3) "..AL["Foreman Thistlenettle"], NPC, 626 };
	};
	TheSunkenTempleEnt = {
		ZoneName = { AL["Sunken Temple"].." ("..AL["Entrance"]..")", 1417 };
		Location = { AL["Swamp of Sorrows"], 8 };
		Acronym = "ST";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE..INDENT..AL["Meeting Stone"] };
		{ BLUE..INDENT..AL["Jade"].." ("..AL["Rare"]..")", NPC, 1063 };
		{ BLUE.."B) "..AL["Sunken Temple"], ZONE, 1417 };
		{ GREY.."1) "..AL["Kazkaz the Unholy"].." ("..AL["Rare"]..", "..AL["Upper"]..")", NPC, 5401 };
		{ GREY.."2) "..AL["Zekkis"].." ("..AL["Rare"]..", "..AL["Lower"]..")", NPC, 5400 };
		{ GREY.."3) "..AL["Veyzhak the Cannibal"].." ("..AL["Rare"]..")", NPC, 5399 };
	};
	UldamanEnt = {
		ZoneName = { AL["Uldaman"].." ("..AL["Entrance"]..")", 1337 };
		Location = { AL["Badlands"], 3 };
		Acronym = "Ulda";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Uldaman"], ZONE, 1337 };
		{ GREY.."1) "..AL["Hammertoe Grez"], NPC, 2909 };
		{ GREY.."2) "..AL["Magregan Deepshadow"].." ("..AL["Wanders"]..")", NPC, 2932 };
		{ GREY.."3) "..AL["Tablet of Ryun'Eh"], ITEM, 4631 };
		{ GREY.."4) "..AL["Krom Stoutarm's Chest"], OBJECT, 124389 };
		{ GREY.."5) "..AL["Garrett Family Chest"], OBJECT, 124388 };
		{ GREN.."1') "..AL["Digmaster Shovelphlange"].." ("..AL["Rare"]..", "..AL["Varies"]..")", NPC, 7057 };
	};
	WailingCavernsEnt = {
		ZoneName = { AL["Wailing Caverns"].." ("..AL["Entrance"]..")", 718 };
		Location = { AL["The Barrens"], 17 };
		Acronym = "WC";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Wailing Caverns"], ZONE, 718 };
		{ GREY.."1) "..AL["Mad Magglish"].." ("..AL["Varies"]..")", NPC, 3655 };
		{ GREY.."2) "..AL["Trigore the Lasher"].." ("..AL["Rare"]..")", NPC, 3652 };
		{ GREY.."3) "..AL["Boahn"].." ("..AL["Rare"]..")", NPC, 3672 };
		{ "" };
		{ ORNG..AL["Above the Entrance:"] };
		{ GREY..INDENT..AL["Ebru"], NPC, 5768 };
		{ GREY..INDENT..AL["Nalpak"], NPC, 5767 };
		{ GREY..INDENT..AL["Kalldan Felmoon"], NPC, 5783 };
		{ GREY..INDENT..AL["Waldor"], NPC, 5784 };
	};
	DireMaulEnt = {
		ZoneName = { AL["Dire Maul"].." ("..AL["Entrance"]..")", 2557 };
		Location = { AL["Feralas"], 357 };
		Acronym = "DM";
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Dire Maul"].." ("..AL["East"]..")", ZONE, 2557 };
		{ BLUE.."C) "..AL["Dire Maul"].." ("..AL["North"]..")", ZONE, 2557 };
		{ BLUE.."D) "..AL["Dire Maul"].." ("..AL["West"]..")", ZONE, 2557 };
		{ GREY.."1) "..AL["Dire Pool"] };
		{ GREY.."2) "..AL["Dire Maul Arena"] };
		{ GREY..INDENT..AL["Mushgog"].." ("..AL["Rare"]..", "..AL["Random"]..")", NPC, 11447 };
		{ GREY..INDENT..AL["Skarr the Unbreakable"].." ("..AL["Rare"]..", "..AL["Random"]..")", NPC, 11498 };
		{ GREY..INDENT..AL["The Razza"].." ("..AL["Rare"]..", "..AL["Random"]..")", NPC, 11497 };
		{ GREY..INDENT..AL["Elder Mistwalker"].." ("..AL["Lunar Festival"]..")", NPC, 15587 };
		{ GREY.."3) "..AL["Griniblix the Spectator"], NPC, 14395 };
	};
	SMEnt = {
		ZoneName = { AL["Scarlet Monastery"].." ("..AL["Entrance"]..")", 796 };
		Location = { AL["Tirisfal Glades"], 85 };
		Acronym = "SM";
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Graveyard"], ZONE, 796 };
		{ BLUE.."C) "..AL["Cathedral"], ZONE, 796 };
		{ BLUE.."D) "..AL["Armory"], ZONE, 796 };
		{ BLUE.."E) "..AL["Library"], ZONE, 796 };
	};
	Azuregos = {
		ZoneName = { AL["Azuregos"], NPC, 6109 };
		Location = { AL["Azshara"], ZONE, 16 };
		{ GREY.."1) "..AL["Azuregos"], NPC, 6109 };
		{ GREY..INDENT..AL["Spirit of Azuregos"], NPC, 15481 };
	};
	FourDragons = {
		ZoneName = { AL["Emerald Dragons"] };
		Location = { AL["Various"] };
		{ GREY.."1) "..AL["Duskwood"], ZONE, 10 };
		{ GREY.."2) "..AL["The Hinterlands"], ZONE, 47 };
		{ GREY.."3) "..AL["Feralas"], ZONE, 357 };
		{ GREY.."4) "..AL["Ashenvale"], ZONE, 331 };
		{ "" };
		{ GREN..INDENT..AL["Lethon"], NPC, 14888 };
		{ GREN..INDENT..AL["Emeriss"], NPC, 14889 };
		{ GREN..INDENT..AL["Taerar"], NPC, 14890 };
		{ GREN..INDENT..AL["Ysondre"], NPC, 14887 };
		{ "" };
		{ GREY..INDENT..AL["Emerald Dragons Trash"] };
	};
	LordKazzak = {
		ZoneName = { AL["Lord Kazzak"], NPC, 18728 };
		Location = { AL["Blasted Lands"], ZONE, 4 };
		{ GREY.."1) "..AL["Lord Kazzak"], NPC, 18728 };
		{ GREY.."2) "..AL["Nethergarde Keep"] };
	};
	Nerubian = {
		ZoneName = { AL["Nerubian Overseer"], NPC, 16184 };
		Location = { AL["Eastern Plaguelands"], ZONE, 139 };
		{ GREY.."1) "..AL["Nerubian Overseer"], NPC, 16184 };
	};
	Reaver = {
		ZoneName = { AL["Dark Reaver of Karazhan"], NPC, 80936 };
		Location = { AL["Deadwind Pass"], ZONE, 41 };
		{ GREY.."1) "..AL["Dark Reaver of Karazhan"], NPC, 80936 };
	};
		Ostarius = {
		ZoneName = { AL["Ostarius"], NPC, 80935 };
		Location = { AL["Tanaris"], ZONE, 440 };
		{ GREY.."1) "..AL["Ostarius"], NPC, 80935 };
	};
		Concavius = {
		ZoneName = { AL["Concavius"], NPC, 92213 };
		Location = { AL["Desolace"], ZONE, 405 };
		{ GREY.."1) "..AL["Concavius"], NPC, 92213 };
	};
	CowKing = {
		ZoneName = { AL["Moo"], NPC, 91799 };
		Location = { AL["Moomoo Grove"], ZONE, -1 };
		{ GREY.."1) "..AL["Moo"], NPC, 91799 };
	};
	Clackora = {
		ZoneName = { AL["Cla'ckora"], NPC, -1 };
		Location = { AL["Azshara"], ZONE, 16 };
		{ GREY.."1) "..AL["Cla'ckora"], NPC, -1 };
	};
	AlteracValleyNorth = {
		ZoneName = { AL["Alterac Valley"].." ("..AL["North"]..")", 2597 };
		Acronym = "AV";
		Location = { AL["Alterac Mountains"], 36 };
		LevelRange = "51-60";
		MinLevel = "51";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["Stormpike Guard"], FACTION, 730 };
		{ BLUE.."A) "..AL["Entrance"] };
		{ BLUE.."B) "..AL["Dun Baldar"] };
		{ BLUE..INDENT..AL["Vanndar Stormpike"], NPC, 11948 };
		{ BLUE..INDENT..AL["Dun Baldar North Marshal"], NPC, 14762 };
		{ BLUE..INDENT..AL["Dun Baldar South Marshal"], NPC, 14763 };
		{ BLUE..INDENT..AL["Icewing Marshal"], NPC, 14764 };
		{ BLUE..INDENT..AL["Stonehearth Marshal"], NPC, 14765 };
		{ BLUE..INDENT..AL["Iceblood Marshal"], NPC, 14766 };
		{ BLUE..INDENT..AL["Tower Point Marshal"], NPC, 14767 };
		{ BLUE..INDENT..AL["East Frostwolf Marshal"], NPC, 14768 };
		{ BLUE..INDENT..AL["West Frostwolf Marshal"], NPC, 14769 };
		{ BLUE..INDENT..AL["Prospector Stonehewer"], NPC, 13816 };
		{ _RED.."1) "..AL["Irondeep Mine"] };
		{ GREY..INDENT..AL["Morloch"].." ("..AL["Neutral"]..")", NPC, 11657 };
		{ GREY..INDENT..AL["Umi Thorson"].." ("..BF["Alliance"]..")", NPC, 13078 };
		{ GREY..INDENT..AL["Keetar"].." ("..BF["Horde"]..")", NPC, 13079 };
		{ GREY.."2) "..AL["Arch Druid Renferal"], NPC, 13442 };
		{ ORNG.."3) "..AL["Dun Baldar North Bunker"] };
		{ GREY..INDENT..AL["Wing Commander Mulverick"].." ("..BF["Horde"]..")", NPC, 13181 };
		{ GREY.."4) "..AL["Murgot Deepforge"], NPC, 13257 };
		{ GREY..INDENT..AL["Dirk Swindle"], NPC, 14188 };
		{ GREY..INDENT..AL["Athramanis"], NPC, 14187 };
		{ GREY..INDENT..AL["Lana Thunderbrew"], NPC, 4257 };
		{ _RED.."5) "..AL["Stormpike Aid Station"] };
		{ GREY.."6) "..AL["Stormpike Stable Master"], NPC, 13617 };
		{ GREY..INDENT..AL["Stormpike Ram Rider Commander"], NPC, 13577 };
		{ GREY..INDENT..AL["Svalbrad Farmountain"], NPC, 5135 };
		{ GREY..INDENT..AL["Kurdrum Barleybeard"], NPC, 5139 };
		{ GREY.."7) "..AL["Stormpike Quartermaster"], NPC, 12096 };
		{ GREY..INDENT..AL["Jonivera Farmountain"], NPC, 5134 };
		{ GREY..INDENT..AL["Brogus Thunderbrew"], NPC, 4255 };
		{ GREY.."8) "..AL["Wing Commander Ichman"].." ("..AL["Rescued"]..")", NPC, 13437 };
		{ GREY..INDENT..AL["Wing Commander Slidore"].." ("..AL["Rescued"]..")", NPC, 13438 };
		{ GREY..INDENT..AL["Wing Commander Vipore"].." ("..AL["Rescued"]..")", NPC, 13439 };
		{ ORNG.."9) "..AL["Dun Baldar South Bunker"] };
		{ GREY..INDENT..AL["Corporal Noreg Stormpike"], NPC, 13447 };
		{ GREY..INDENT..AL["Gaelden Hammersmith"], NPC, 13216 };
		{ _RED.."10) "..AL["Stormpike Graveyard"] };
		{ GREY.."11) "..AL["Icewing Cavern"] };
		{ GREY..INDENT..AL["Stormpike Banner"], OBJECT, 179024 };
		{ GREY.."12) "..AL["Stormpike Lumber Yard"] };
		{ GREY..INDENT..AL["Wing Commander Jeztor"].." ("..BF["Horde"]..")", NPC, 13180 };
		{ ORNG.."13) "..AL["Icewing Bunker"] };
		{ GREY..INDENT..AL["Wing Commander Guse"].." ("..BF["Horde"]..")", NPC, 13179 };
		{ _RED.."14) "..AL["Stonehearth Graveyard"] };
		{ GREY.."15) "..AL["Stormpike Ram Rider Commander"], NPC, 13577 };
		{ ORNG.."16) "..AL["Stonehearth Outpost"] };
		{ GREY..INDENT..AL["Captain Balinda Stonehearth"], NPC, 11949 };
		{ _RED.."17) "..AL["Snowfall Graveyard"] };
		{ GREY..INDENT..AL["Ichman's Beacon"], ITEM, 17505 };
		{ GREY..INDENT..AL["Mulverick's Beacon"].." ("..BF["Horde"]..")", ITEM, 17323 };
		{ GREY..INDENT..AL["Korrak the Bloodrager"], NPC, 12159 };
		{ ORNG.."18) "..AL["Stonehearth Bunker"] };
		{ GREY.."19) "..AL["Ivus the Forest Lord"].." ("..AL["Summon"]..")", NPC, 13419 };
		{ GREY.."20) "..AL["Western Crater"] };
		{ GREY..INDENT..AL["Vipore's Beacon"], ITEM, 17506 };
		{ GREY..INDENT..AL["Jeztor's Beacon"].." ("..BF["Horde"]..")", ITEM, 17325 };
		{ GREY.."21) "..AL["Eastern Crater"] };
		{ GREY..INDENT..AL["Slidore's Beacon"], ITEM, 17507 };
		{ GREY..INDENT..AL["Guse's Beacon"].." ("..BF["Horde"]..")", ITEM, 17324 };
		{ GREY.."22) "..AL["Steamsaw"].." ("..BF["Horde"]..")", OBJECT, 178664 };
		{ "" };
		{ GREN..INDENT..AL["Friendly Reputation Rewards"] };
		{ GREN..INDENT..AL["Honored Reputation Rewards"] };
		{ GREN..INDENT..AL["Revered Reputation Rewards"] };
		{ GREN..INDENT..AL["Exalted Reputation Rewards"] };
		{ "" };
		{ _RED..AL["Red"]..": ".._RED..AL["Graveyards, Capturable Areas"] };
		{ ORNG..AL["Orange"]..": "..ORNG..AL["Bunkers, Towers, Destroyable Areas"] };
		{ GREY..AL["White"]..": "..GREY..AL["Assault NPCs, Quest Areas"] };
	};
	AlteracValleySouth = {
		ZoneName = { AL["Alterac Valley"].." ("..AL["South"]..")", 2597 };
		Acronym = "AV";
		Location = { AL["Hillsbrad Foothills"], 36 };
		LevelRange = "51-60";
		MinLevel = "51";
		PlayerLimit = "40";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["Frostwolf Clan"], FACTION, 729 };
		{ BLUE.."A) "..AL["Entrance"].." ("..BF["Horde"]..")" };
		{ BLUE.."B) "..AL["Frostwolf Keep"] };
		{ BLUE..INDENT..AL["Drek'Thar"], NPC, 11946 };
		{ BLUE..INDENT..AL["Duros"], NPC, 12122 };
		{ BLUE..INDENT..AL["Drakan"], NPC, 12121 };
		{ BLUE..INDENT..AL["West Frostwolf Warmaster"], NPC, 14777 };
		{ BLUE..INDENT..AL["East Frostwolf Warmaster"], NPC, 14772 };
		{ BLUE..INDENT..AL["Tower Point Warmaster"], NPC, 14776 };
		{ BLUE..INDENT..AL["Iceblood Warmaster"], NPC, 14773 };
		{ BLUE..INDENT..AL["Stonehearth Warmaster"], NPC, 14775 };
		{ BLUE..INDENT..AL["Icewing Warmaster"], NPC, 14774 };
		{ BLUE..INDENT..AL["Dun Baldar North Warmaster"], NPC, 14770 };
		{ BLUE..INDENT..AL["Dun Baldar South Warmaster"], NPC, 14771 };
		{ GREY.."1) "..AL["Lokholar the Ice Lord"].." ("..AL["Summon"]..")", NPC, 13256 };
		{ ORNG.."2) "..AL["Iceblood Garrison"] };
		{ GREY..INDENT..AL["Captain Galvangar"], NPC, 11947 };
		{ ORNG.."3) "..AL["Iceblood Tower"] };
		{ _RED.."4) "..AL["Iceblood Graveyard"] };
		{ GREY..INDENT..AL["Wing Commander Ichman"].." ("..BF["Alliance"]..")", NPC, 13437 };
		{ ORNG.."5) "..AL["Tower Point"] };
		{ GREY..INDENT..AL["Wing Commander Slidore"].." ("..BF["Alliance"]..")", NPC, 13438 };
		{ GREY.."6) "..AL["Coldtooth Mine"] };
		{ GREY..INDENT..AL["Taskmaster Snivvle"].." ("..AL["Neutral"]..")", NPC, 11677 };
		{ GREY..INDENT..AL["Masha Swiftcut"].." ("..BF["Horde"]..")", NPC, 13088 };
		{ GREY..INDENT..AL["Aggi Rumblestomp"].." ("..BF["Alliance"]..")", NPC, 13086 };
		{ _RED.."7) "..AL["Frostwolf Graveyard"] };
		{ GREY.."8) "..AL["Wing Commander Vipore"].." ("..BF["Alliance"]..")", NPC, 13439 };
		{ GREY..INDENT..AL["Jotek"], NPC, 13798 };
		{ GREY..INDENT..AL["Smith Regzar"], NPC, 13176 };
		{ GREY..INDENT..AL["Primalist Thurloga"], NPC, 13236 };
		{ GREY..INDENT..AL["Sergeant Yazra Bloodsnarl"], NPC, 13448 };
		{ GREY.."9) "..AL["Frostwolf Stable Master"], NPC, 13616 };
		{ GREY..INDENT..AL["Frostwolf Wolf Rider Commander"], NPC, 13441 };
		{ GREY.."10) "..AL["Frostwolf Quartermaster"], NPC, 12097 };
		{ ORNG.."11) "..AL["West Frostwolf Tower"] };
		{ ORNG.."12) "..AL["East Frostwolf Tower"] };
		{ GREY.."13) "..AL["Wing Commander Guse"].." ("..AL["Rescued"]..")", NPC, 13179 };
		{ GREY..INDENT..AL["Wing Commander Jeztor"].." ("..AL["Rescued"]..")", NPC, 13180 };
		{ GREY..INDENT..AL["Wing Commander Mulverick"].." ("..AL["Rescued"]..")", NPC, 13181 };
		{ _RED.."14) "..AL["Frostwolf Relief Hut"] };
		{ GREY.."15) "..AL["Wildpaw Cavern"] };
		{ GREY..INDENT..AL["Frostwolf Banner"], OBJECT, 179025 };
		{ GREY.."16) "..AL["Steamsaw"].." ("..BF["Alliance"]..")", OBJECT, 178665 };
		{ "" };
		{ GREN..INDENT..AL["Friendly Reputation Rewards"] };
		{ GREN..INDENT..AL["Honored Reputation Rewards"] };
		{ GREN..INDENT..AL["Revered Reputation Rewards"] };
		{ GREN..INDENT..AL["Exalted Reputation Rewards"] };
		{ "" };
		{ _RED..AL["Red"]..": ".._RED..AL["Graveyards, Capturable Areas"] };
		{ ORNG..AL["Orange"]..": "..ORNG..AL["Bunkers, Towers, Destroyable Areas"] };
		{ GREY..AL["White"]..": "..GREY..AL["Assault NPCs, Quest Areas"] };
	};
	ArathiBasin = {
		ZoneName = { AL["Arathi Basin"], 3358 };
		Acronym = "AB";
		Location = { AL["Arathi Highlands"], 45 };
		LevelRange = "20-60";
		MinLevel = "20";
		PlayerLimit = "15";
		Continent = AL["Eastern Kingdoms"];
		{ ORNG..AL["Reputation"]..": "..BF["The Defilers"].." ("..BF["Horde"]..")", FACTION, 510 };
		{ ORNG..AL["Reputation"]..": "..BF["The League of Arathor"].." ("..BF["Alliance"]..")", FACTION, 509 };
		{ BLUE.."A) "..AL["Trollbane Hall"].." ("..BF["Alliance"]..")" };
		{ BLUE.."B) "..AL["Defiler's Den"].." ("..BF["Horde"]..")" };
		{ GREY.."1) "..AL["Stables"] };
		{ GREY.."2) "..AL["Gold Mine"] };
		{ GREY.."3) "..AL["Blacksmith"] };
		{ GREY.."4) "..AL["Lumber Mill"] };
		{ GREY.."5) "..AL["Farm"] };
		{ "" };
		{ GREN..INDENT..AL["Friendly Reputation Rewards"] };
		{ GREN..INDENT..AL["Honored Reputation Rewards"] };
		{ GREN..INDENT..AL["Revered Reputation Rewards"] };
		{ GREN..INDENT..AL["Exalted Reputation Rewards"] };
	};
	WarsongGulch = {
		ZoneName = { AL["Warsong Gulch"], 3277 };
		Acronym = "WSG";
		Location = { AL["Ashenvale"].." / "..AL["The Barrens"], 331, 17 };
		LevelRange = "10-60";
		MinLevel = "10";
		PlayerLimit = "10";
		Continent = AL["Kalimdor"];
		{ ORNG..AL["Reputation"]..": "..BF["Warsong Outriders"].." ("..BF["Horde"]..")", FACTION, 889 };
		{ ORNG..AL["Reputation"]..": "..BF["Silverwing Sentinels"].." ("..BF["Alliance"]..")", FACTION, 890 };
		{ BLUE.."A) "..AL["Silverwing Hold"].." ("..BF["Alliance"]..")" };
		{ BLUE.."B) "..AL["Warsong Lumber Mill"].." ("..BF["Horde"]..")" };
		{ "" };
		{ GREN..INDENT..AL["Friendly Reputation Rewards"] };
		{ GREN..INDENT..AL["Honored Reputation Rewards"] };
		{ GREN..INDENT..AL["Revered Reputation Rewards"] };
		{ GREN..INDENT..AL["Exalted Reputation Rewards"] };
	};
	DLEast = {
		ZoneName = { AL["Dungeon Locations"].." ("..AL["Eastern Kingdoms"]..")" };
		Location = { AL["Eastern Kingdoms"] };
		Continent = AL["Eastern Kingdoms"];
		{ BLUE.."A) "..AL["Alterac Valley"]..", "..ORNG..AL["Alterac Mountains"].." / "..AL["Hillsbrad Foothills"], ZONE, 2597, 36, 267 };
		{ BLUE.."B) "..AL["Arathi Basin"]..", "..ORNG..AL["Arathi Highlands"], ZONE, 3358, 45 };
		{ BLUE.."C) "..AL["Blood Ring Arena"]..", "..ORNG..AL["Stranglethorn Vale"], ZONE, 19, 33 };
		{ GREY.."1) "..AL["Scarlet Monastery"]..", "..ORNG..AL["Tirisfal Glades"], ZONE, 796, 85 };
		{ GREY.."2) "..AL["Stratholme"]..", "..ORNG..AL["Eastern Plaguelands"], ZONE, 2017, 139 };
		{ GREY.."3) "..AL["Naxxramas"]..", "..ORNG..AL["Eastern Plaguelands"], ZONE, 3456, 139 };
		{ GREY.."4) "..AL["Scholomance"]..", "..ORNG..AL["Western Plaguelands"], ZONE, 2057, 28 };
		{ GREY.."5) "..AL["Shadowfang Keep"]..", "..ORNG..AL["Silverpine Forest"], ZONE, 209, 130 };
		{ GREY.."6) "..AL["Gilneas City"]..", "..ORNG..AL["Gilneas"], ZONE, 133, 1 };
		{ GREY.."7) "..AL["Dragonmaw Retreat"]..", "..ORNG..AL["Wetlands"] };
		{ GREY.."8) "..AL["Gnomeregan"]..", "..ORNG..AL["Dun Morogh"], ZONE, 133, 1 };
		{ GREY.."9) "..AL["Uldaman"]..", "..ORNG..AL["Badlands"], ZONE, 1337, 3 };
		{ GREY.."10) "..AL["Blackwing Lair"]..", "..ORNG..AL["Blackrock Spire"], ZONE, 2677, 1583 };
		{ GREY..INDENT..AL["Blackrock Depths"]..", "..ORNG..AL["Blackrock Mountain"], ZONE, 1584, 25 };
		{ GREY..INDENT..AL["Blackrock Spire"]..", "..ORNG..AL["Blackrock Mountain"], ZONE, 1583, 25 };
		{ GREY..INDENT..AL["Molten Core"]..", "..ORNG..AL["Blackrock Depths"], ZONE, 2717, 1584 };
		{ GREY.."11) "..AL["Hateforge Quarry"]..", "..ORNG..AL["Burning Steppes"], ZONE, 717, 1519 };
		{ GREY.."12) "..AL["The Stockade"]..", "..ORNG..AL["Stormwind City"], ZONE, 717, 1519 };
		{ GREY..INDENT..AL["Stormwind Vault"]..", "..ORNG..AL["Stormwind City"], ZONE, 717, 1519 };
		{ GREY.."13) "..AL["Stormwrought Ruins"]..", "..ORNG..AL["Balor"] };
		{ GREY.."14) "..AL["The Deadmines"]..", "..ORNG..AL["Westfall"], ZONE, 1581, 40 };
		{ GREY.."15) "..AL["Karazhan Crypt"]..", "..ORNG..AL["Deadwind Pass"], ZONE, 1581, 40 };
		{ GREY..INDENT..AL["Lower Karazhan Halls"]..", "..ORNG..AL["Deadwind Pass"], ZONE, 1581, 40 };
		{ GREY..INDENT..AL["Tower of Karazhan"]..", "..ORNG..AL["Deadwind Pass"] };
		{ GREY.."16) "..AL["Sunken Temple"]..", "..ORNG..AL["Swamp of Sorrows"], ZONE, 1417, 8 };
		{ GREY.."17) "..AL["Zul'Gurub"]..", "..ORNG..AL["Stranglethorn Vale"], ZONE, 19, 33 };
		{ BLUE..AL["Blue"]..": "..ORNG..AL["Battlegrounds"] };
		{ GREY..AL["White"]..": "..ORNG..AL["Instances"] };
	};
	DLWest = {
		ZoneName = { AL["Dungeon Locations"].." ("..AL["Kalimdor"]..")" };
		Location = { AL["Kalimdor"] };
		Continent = AL["Kalimdor"];
		{ BLUE.."A) "..AL["Warsong Gulch"]..", "..ORNG..AL["The Barrens"].." / "..AL["Ashenvale"], ZONE, 3277, 17, 331 };
		{ BLUE.."B) "..AL["Sunnyglade Valley"]..", "..ORNG..AL["Caverns of Time"], ZONE, 3277, 17, 331 };
		{ GREY.."1) "..AL["Emerald Sanctum"]..", "..ORNG..AL["Hyjal"], ZONE, 719, 331 };
		{ GREY.."2) "..AL["Blackfathom Deeps"]..", "..ORNG..AL["Ashenvale"], ZONE, 719, 331 };
		{ GREY.."3) "..AL["The Crescent Grove"]..", "..ORNG..AL["Ashenvale"], ZONE, 719, 331 };
		{ GREY.."4) "..AL["Ragefire Chasm"]..", "..ORNG..AL["Orgrimmar"], ZONE, 2437, 1637 };
		{ GREY.."5) "..AL["Wailing Caverns"]..", "..ORNG..AL["The Barrens"], ZONE, 718, 17 };
		{ GREY.."6) "..AL["Maraudon"]..", "..ORNG..AL["Desolace"], ZONE, 2100, 405 };
		{ GREY.."7) "..AL["Dire Maul"]..", "..ORNG..AL["Feralas"], ZONE, 2557, 357 };
		{ GREY.."8) "..AL["Razorfen Kraul"]..", "..ORNG..AL["The Barrens"], ZONE, 491, 17 };
		{ GREY.."9) "..AL["Razorfen Downs"]..", "..ORNG..AL["The Barrens"], ZONE, 722, 17 };
		{ GREY.."10) "..AL["Onyxia's Lair"]..", "..ORNG..AL["Dustwallow Marsh"], ZONE, 2159, 15 };
		{ GREY.."11) "..AL["Zul'Farrak"]..", "..ORNG..AL["Tanaris"], ZONE, 978, 440 };
		{ GREY.."12) "..AL["Black Morass"]..", "..ORNG..AL["Caverns of Time"], ZONE, 978, 440 };
		{ GREY.."13) "..AL["Ruins of Ahn'Qiraj"]..", "..ORNG..AL["Silithus"], ZONE, 3429, 1377 };
		{ GREY..INDENT..AL["Temple of Ahn'Qiraj"]..", "..ORNG..AL["Silithus"], ZONE, 3428, 1377 };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ "" };
		{ BLUE..AL["Blue"]..": "..ORNG..AL["Battlegrounds"] };
		{ GREY..AL["White"]..": "..ORNG..AL["Instances"] };
	};
	FPAllianceEast = {
		ZoneName = { BF["Alliance"].." ("..AL["Eastern Kingdoms"]..")" };
		Location = { AL["Eastern Kingdoms"] };
		{ GREY.."1) "..AL["Alah'Thalas"]..", "..BLUE..AL["Thalassian Highlands"], ZONE, 33 };
		{ GREY.."2) "..AL["Light's Hope Chapel"]..", "..BLUE..AL["Eastern Plaguelands"], ZONE, 139 };
		{ GREY.."3) "..AL["Chillwind Point"]..", "..BLUE..AL["Western Plaguelands"], ZONE, 28 };
		{ GREY.."4) "..AL["Aerie Peak"]..", "..BLUE..AL["The Hinterlands"], ZONE, 47 };
		{ GREY.."5) "..AL["Southshore"]..", "..BLUE..AL["Hillsbrad Foothills"], ZONE, 267 };
		{ GREY.."6) "..AL["Refuge Pointe"]..", "..BLUE..AL["Arathi Highlands"], ZONE, 45 };
		{ GREY.."7) "..AL["Ravenshire"]..", "..BLUE..AL["Gilneas"], ZONE, 33 };
		{ GREY.."8) "..AL["Menethil Harbor"]..", "..BLUE..AL["Wetlands"], ZONE, 11 };
		{ GREY.."9) "..AL["Dun Agrath"]..", "..BLUE..AL["Wetlands"] };
		{ GREY.."10) "..AL["Dun Kithas"]..", "..BLUE..AL["Grim Reaches"] };
		{ GREY.."11) "..AL["Thelsamar"]..", "..BLUE..AL["Loch Modan"], ZONE, 38 };
		{ GREY.."12) "..AL["Ironforge Airfields"]..", "..BLUE..AL["Dun Morogh"], ZONE, 1 };
		{ GREY.."13) "..AL["Ironforge"]..", "..BLUE..AL["Dun Morogh"], ZONE, 1 };
		{ GREY.."14) "..AL["Gnomeregan Reclamation Facility"]..", "..BLUE..AL["Dun Morogh"], ZONE, 1 };
		{ GREY.."15) "..AL["Thorium Point"]..", "..BLUE..AL["Searing Gorge"], ZONE, 51 };
		{ GREY.."16) "..AL["Ambershire"]..", "..BLUE..AL["Northwind"] };
		{ GREY.."17) "..AL["Morgan's Vigil"]..", "..BLUE..AL["Burning Steppes"], ZONE, 46 };
		{ GREY.."18) "..AL["Lakeshire"]..", "..BLUE..AL["Redridge Mountains"], ZONE, 44 };
		{ GREY.."19) "..AL["Stormwind City"]..", "..BLUE..AL["Elwynn Forest"], ZONE, 12 };
		{ GREY.."20) "..AL["SI:7 Outpost"]..", "..BLUE..AL["Balor"] };
		{ GREY.."21) "..AL["Sentinel Hill"]..", "..BLUE..AL["Westfall"], ZONE, 40 };
		{ GREY.."22) "..AL["Darkshire"]..", "..BLUE..AL["Duskwood"], ZONE, 10 };
		{ GREY.."23) "..AL["Nethergarde Keep"]..", "..BLUE..AL["Blasted Lands"], ZONE, 4 };
		{ GREY.."24) "..AL["Booty Bay"]..", "..BLUE..AL["Stranglethorn Vale"], ZONE, 33 };
		{ GREY.."25) "..AL["Caelan's Rest"]..", "..BLUE..AL["Lapidis Isle"], ZONE, 33 };
	};
	FPAllianceWest = {
		ZoneName = { BF["Alliance"].." ("..AL["Kalimdor"]..")" };
		Location = { AL["Kalimdor"] };
		{ GREY.."1) "..AL["Rut'Theran Village"]..", "..BLUE..AL["Teldrassil"], ZONE, 141 };
		{ GREY.."2) "..GREN..AL["Nighthaven"]..GREY..", "..BLUE..AL["Moonglade"]..GREN.." ("..AL["Druid-only"]..")", ZONE, 493 };
		{ GREY..INDENT..AL["South of the path along Lake Elune'ara"]..", "..BLUE..AL["Moonglade"], ZONE, 493 };
		{ GREY.."3) "..AL["Everlook"]..", "..BLUE..AL["Winterspring"], ZONE, 618 };
		{ GREY.."4) "..AL["Auberdine"]..", "..BLUE..AL["Darkshore"], ZONE, 148 };
		{ GREY.."5) "..AL["Talonbranch Glade"]..", "..BLUE..AL["Felwood"], ZONE, 361 };
		{ GREY.."6) "..AL["Nordanaar"]..", "..BLUE..AL["Hyjal"], ZONE, 440 };
		{ GREY.."7) "..AL["Stonetalon Peak"]..", "..BLUE..AL["Stonetalon Mountains"], ZONE, 406 };
		{ GREY.."8) "..AL["Astranaar"]..", "..BLUE..AL["Ashenvale"], ZONE, 331 };
		{ GREY.."9) "..AL["Talrendis Point"]..", "..BLUE..AL["Azshara"], ZONE, 16 };
		{ GREY.."10) "..AL["Bael Hardul"]..", "..BLUE..AL["Stonetalon Mountains"], ZONE, 440 };
		{ GREY.."11) "..AL["Nijel's Point"]..", "..BLUE..AL["Desolace"], ZONE, 405 };
		{ GREY.."12) "..AL["Ratchet"]..", "..BLUE..AL["The Barrens"], ZONE, 17 };
		{ GREY.."13) "..AL["Theramore Isle"]..", "..BLUE..AL["Dustwallow Marsh"], ZONE, 15 };
		{ GREY.."14) "..AL["Thalanaar"]..", "..BLUE..AL["Feralas"], ZONE, 357 };
		{ GREY.."15) "..AL["Feathermoon Stronghold"]..", "..BLUE..AL["Feralas"], ZONE, 357 };
		{ GREY.."16) "..AL["Cenarion Hold"]..", "..BLUE..AL["Silithus"], ZONE, 1377 };
		{ GREY.."17) "..AL["Marshal's Refuge"]..", "..BLUE..AL["Un'Goro Crater"], ZONE, 490 };
		{ GREY.."18) "..AL["Gadgetzan"]..", "..BLUE..AL["Tanaris"], ZONE, 440 };
		{ GREY.."19) "..AL["Tel Co. Basecamp"]..", "..BLUE..AL["Tel'Abim"], ZONE, 440 };
	};
	FPHordeEast = {
		ZoneName = { BF["Horde"].." ("..AL["Eastern Kingdoms"]..")" };
		Location = { AL["Eastern Kingdoms"] };
		{ GREY.."1) "..AL["Light's Hope Chapel"]..", ".._RED..AL["Eastern Plaguelands"], ZONE, 139 };
		{ GREY.."2) "..AL["Undercity"]..", ".._RED..AL["Tirisfal Glades"], ZONE, 85 };
		{ GREY.."3) "..AL["Steepcliff Port"]..", ".._RED..AL["Tirisfal Glades"] };
		{ GREY.."4) "..AL["The Sepulcher"]..", ".._RED..AL["Silverpine Forest"], ZONE, 130 };
		{ GREY.."5) "..AL["Tarren Mill"]..", ".._RED..AL["Hillsbrad Foothills"], ZONE, 267 };
		{ GREY.."6) "..AL["Revantusk Village"]..", ".._RED..AL["The Hinterlands"], ZONE, 47 };
		{ GREY.."7) "..AL["Hammerfall"]..", ".._RED..AL["Arathi Highlands"], ZONE, 45 };
		{ GREY.."8) "..AL["Stillward Church"]..", ".._RED..AL["Gilneas"], ZONE, 33 };
		{ GREY.."9) "..AL["Shatterblade Post"]..", ".._RED..AL["Grim Reaches"] };
		{ GREY.."10) "..AL["Kargath"]..", ".._RED..AL["Badlands"], ZONE, 3 };
		{ GREY.."11) "..AL["Thorium Point"]..", ".._RED..AL["Searing Gorge"], ZONE, 51 };
		{ GREY.."12) "..AL["Flame Crest"]..", ".._RED..AL["Burning Steppes"], ZONE, 46 };
		{ GREY.."13) "..AL["Stormbreaker Point"]..", ".._RED..AL["Balor"] };
		{ GREY.."14) "..AL["Stonard"]..", ".._RED..AL["Swamp of Sorrows"], ZONE, 8 };
		{ GREY.."15) "..AL["Grom'Gol Base Camp"]..", ".._RED..AL["Stranglethorn Vale"], ZONE, 33 };
		{ GREY.."16) "..AL["Booty Bay"]..", ".._RED..AL["Stranglethorn Vale"], ZONE, 33 };
		{ GREY.."17) "..AL["Maul'ogg Refuge"]..", ".._RED..AL["Gillijim's Isle"], ZONE, 33 };
	};
	FPHordeWest = {
		ZoneName = { BF["Horde"].." ("..AL["Kalimdor"]..")" };
		Location = { AL["Kalimdor"] };
		{ GREY.."1) "..GREN..AL["Nighthaven"]..GREY..", ".._RED..AL["Moonglade"]..GREN.." ("..AL["Druid-only"]..")", ZONE, 493 };
		{ GREY..INDENT..AL["West of the path to Timbermaw Hold"]..", ".._RED..AL["Moonglade"], ZONE, 493 };
		{ GREY.."2) "..AL["Everlook"]..", ".._RED..AL["Winterspring"], ZONE, 618 };
		{ GREY.."3) "..AL["Nordanaar"]..", ".._RED..AL["Hyjal"], ZONE, 440 };
		{ GREY.."4) "..AL["Bloodvenom Post"]..", ".._RED..AL["Felwood"], ZONE, 361 };
		{ GREY.."5) "..AL["Valormok"]..", ".._RED..AL["Azshara"], ZONE, 16 };
		{ GREY.."6) "..AL["Orgrimmar"]..", ".._RED..AL["Durotar"], ZONE, 14 };
		{ GREY.."7) "..AL["Splintertree Post"]..", ".._RED..AL["Ashenvale"], ZONE, 331 };
		{ GREY.."8) "..AL["Zoram'gar Outpost"]..", ".._RED..AL["Ashenvale"], ZONE, 331 };
		{ GREY.."9) "..AL["Sun Rock Retreat"]..", ".._RED..AL["Stonetalon Mountains"], ZONE, 406 };
		{ GREY.."10) "..AL["Crossroads"]..", ".._RED..AL["The Barrens"], ZONE, 17 };
		{ GREY.."11) "..AL["Ratchet"]..", ".._RED..AL["The Barrens"], ZONE, 17 };
		{ GREY.."12) "..AL["Thunder Bluff"]..", ".._RED..AL["Mulgore"], ZONE, 215 };
		{ GREY.."13) "..AL["Shadowprey Village"]..", ".._RED..AL["Desolace"], ZONE, 405 };
		{ GREY.."14) "..AL["Camp Taurajo"]..", ".._RED..AL["The Barrens"], ZONE, 17 };
		{ GREY.."15) "..AL["Brackenwall Village"]..", ".._RED..AL["Dustwallow Marsh"], ZONE, 15 };
		{ GREY.."16) "..AL["Mudsprocket"]..", ".._RED..AL["Dustwallow Marsh"], ZONE, 440 };
		{ GREY.."17) "..AL["Freewind Post"]..", ".._RED..AL["Thousand Needles"], ZONE, 400 };
		{ GREY.."18) "..AL["Camp Mojache"]..", ".._RED..AL["Feralas"], ZONE, 357 };
		{ GREY.."19) "..AL["Gadgetzan"]..", ".._RED..AL["Tanaris"], ZONE, 440 };
		{ GREY.."20) "..AL["Tel Co. Basecamp"]..", ".._RED..AL["Tel'Abim"], ZONE, 440 };
		{ GREY.."21) "..AL["Marshal's Refuge"]..", ".._RED..AL["Un'Goro Crater"], ZONE, 490 };
		{ GREY.."22) "..AL["Cenarion Hold"]..", ".._RED..AL["Silithus"], ZONE, 1377 };
		{ GREY.."23) "..AL["Slickwick Oil Rig"]..", ".._RED..AL["Tanaris"] };
	};
	TransportRoutes = {
		ZoneName = { AL["Transport Routes"]};
		Location = { AL["Azeroth"]};
		{ GREY.."1) "..AL["Rut'Theran Village"]..", "..BLUE..AL["Teldrassil"], ZONE, 141 };
		{ GREY.."2) "..AL["Auberdine"]..", "..BLUE..AL["Darkshore"], ZONE, 618 };
		{ GREY.."7) "..AL["Feathermoon Stronghold"]..", "..BLUE..AL["Feralas"], ZONE, 331 };
		{ GREY.."8) "..AL["Theramore Isle"]..", "..BLUE..AL["Dustwallow Marsh"], ZONE, 14 };
		{ GREY.."9) "..AL["Alah'Thalas"]..", "..BLUE..AL["Thalassian Highlands"], ZONE, 406 };
		{ GREY.."12) "..AL["Menethil Harbor"]..", "..BLUE..AL["Wetlands"], ZONE, 405 };
		{ GREY.."13) "..AL["Ironforge"]..", "..BLUE..AL["Dun Morogh"], ZONE, 215 };
		{ GREY.."15) "..AL["Stormwind City"]..", "..BLUE..AL["Elwynn Forest"], ZONE, 15 };
		{ "" };	
		{ GREY.."3) "..AL["Orgrimmar"]..", ".._RED..AL["The Barrens"], ZONE, 440 };
		{ GREY.."4) "..AL["Sparkwater Port"]..", ".._RED..AL["The Barrens"], ZONE, 361 };
		{ GREY.."6) "..AL["Thunder Bluff"]..", ".._RED..AL["Mulgore"], ZONE, 16 };
		{ GREY.."10) "..AL["Undercity"]..", ".._RED..AL["Tirisfal Glades"], ZONE, 17 };
		{ GREY.."11) "..AL["Revantusk Village"]..", ".._RED..AL["The Hinterlands"], ZONE, 17 };
		{ GREY.."14) "..AL["Kargath"]..", ".._RED..AL["Badlands"], ZONE, 17 };
		{ GREY.."16) "..AL["Grom'Gol Base Camp"]..", ".._RED..AL["Stranglethorn Vale"], ZONE, 440 };
		{ "" };	
		{ GREY.."5) "..AL["Ratchet"]..", "..ORNG..AL["The Barrens"], ZONE, 331 };
		{ GREY.."17) "..AL["Booty Bay"]..", "..ORNG..AL["Stranglethorn Vale"], ZONE, 357 };
	};
};